import {days,tasks,phases,resources,milestones,PLAN_VERSION} from './plan.js';
import {LocalStore} from './storage.js';
import {clone,uid,dateKey,validDate,initialState,esc,safeUrl,allTasks,findTask,isFinished,planDates,taskDate,nextStudyDate,blockers,stats,setTaskStatus,recordEvent,timerRemaining,settleTimer,gradeReview,parseBackup,backupEnvelope,validateState,csv,calendarICS,planMarkdown,weeklySummary} from './core.js';
import {icon,button,external,money,hours,clockText,shortDate,fmtTime,empty,notice,navs,shell,renderView} from './views.js';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const store=new LocalStore();
const ctx={store,state:store.state,view:'dashboard',selectedDay:1,compare:[],planMode:'calendar',reviewMode:'due'};
const dialog=$('#dialog');let dialogDirty=false,toastTimer,journalTimer,pendingJournal={},journalDay=1,importCandidate=null,encryptedCandidate=null,installPrompt=null,settling=false,audioContext=null;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function notifyError(e){console.error(e);toast(e?.message||'操作未完成，请检查后重试。');updateStatus();}
function updateStatus(){const s=store.state;ctx.state=s;const el=$('#save-status');if(el){el.innerHTML=`<span class="dot ${store.warning?'warn':''}"></span>${store.mode==='memory'?'仅内存 · 请导出':store.warning?'已保存 · 请检查存储提示':'已保存到此浏览器'}`;el.title=store.warning||('最近写入 '+fmtTime(s.updatedAt));}const st=stats(s);if($('#sidebar-pct'))$('#sidebar-pct').textContent=Math.round(st.earned/180)+'%';if($('#sidebar-progress span'))$('#sidebar-progress span').style.width=st.earned/180+'%';}
function render(){ctx.state=store.state;document.documentElement.dataset.theme=ctx.state.settings.theme;if(!$('#main'))$('#app').innerHTML=shell(ctx);const active=document.activeElement,focusId=active?.id,selection=active?.selectionStart;$('#main').innerHTML=renderView(ctx);$$('.nav-link').forEach(n=>{const current=n.hash==='#'+ctx.view;n.classList.toggle('active',current);if(current)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});$('#crumb').textContent=navs.find(n=>n[0]===ctx.view)?.[1]||'总览';document.title=(navs.find(n=>n[0]===ctx.view)?.[1]||'工作台')+' · RL Mission Control';updateStatus();updateTimerUI();updateNetwork();if(focusId&&$('#'+focusId)&&focusId==='resource-search'){$('#'+focusId).focus();$('#'+focusId).setSelectionRange(selection,selection);}if(ctx.view==='settings')storageInfo();}
async function navigate(view){if(!navs.some(n=>n[0]===view))view='dashboard';await flushJournal();ctx.view=view;if(location.hash!=='#'+view)history.pushState(null,'','#'+view);render();menu(false);window.scrollTo({top:0,behavior:'auto'});}
function menu(open){$('.sidebar')?.classList.toggle('open',open);$('.mobile-scrim')?.classList.toggle('show',open);}
function openDialog(title,html){dialogDirty=false;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;setTimeout(()=>{const f=dialog.querySelector('[autofocus]');if(f)f.focus();},0);}
function closeDialog(force=false){if(!force&&dialogDirty&&!confirm('表单还有未保存内容，确认关闭吗？'))return;dialogDirty=false;dialog.close();}
function download(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function field(label,name,value='',type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input type="${type}" name="${name}" value="${esc(value??'')}" ${extra}></label>`;}
function area(label,name,value='',extra=''){return `<label class="field"><span>${esc(label)}</span><textarea name="${name}" ${extra}>${esc(value??'')}</textarea></label>`;}
function selectField(label,name,options,value){return `<label class="field"><span>${esc(label)}</span><select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
const formActions=(text='保存')=>`<div class="dialog-actions">${button('取消','close')}<button class="btn primary" type="submit">${icon('check',15)}${text}</button></div>`;
function taskDialog(id){const s=store.state,t=findTask(id,s);if(!t)throw Error('任务不存在');const v=s.tasks[id]||{},issues=blockers(t,s),actual=Object.values(s.sessions).filter(x=>x.taskId===id).reduce((a,x)=>a+x.minutes,0);openDialog(t.title,`<div class="row wrap"><span class="pill">Day ${t.day}</span><span class="pill gray">${esc(t.kind)}</span>${v.status==='waived'?'<span class="pill orange">掌握豁免 · 不计完成学时</span>':''}</div><div class="stat-inline"><div><small>计划投入</small><b>${t.minutes} min</b></div><div><small>实际记录</small><b>${hours(actual)} h</b></div><div><small>计划日期</small><b>${shortDate(taskDate(t,s))}</b></div></div>${issues.length?`<div class="notice warn">${icon('lock',16)}<div><p>前置未完成；允许浏览，严格模式下暂不能标记完成。</p><div class="row wrap mt-sm">${issues.map(p=>button(p.label,p.id.startsWith('gate-')?'roadmap':'task',p.id,'sm')).join('')}</div></div></div>`:notice('前置已满足。完成后请对照下方验收标准自行确认。')}<section class="dialog-section"><h3>本项要做什么</h3><p>${esc(t.description)}</p></section><section class="dialog-section"><h3>验收标准</h3><p>${esc(t.acceptance)}</p></section><section class="dialog-section"><h3>按顺序打开资料</h3>${(t.resources||[]).map(rid=>{const r=resources.find(x=>x.id===rid);return r?`<div class="resource-link">${external(r.url,r.title)}<span class="tiny muted">${r.type}</span></div>`:'';}).join('')||'<p>自定义任务没有预设资料，请在笔记中补充。</p>'}</section><div class="insight"><strong>卡住时的回退路线</strong>${esc(t.fallback||'先缩小到可验证的最小例子。')}</div><form data-form="task" data-id="${esc(id)}" class="mt"><div class="form-grid">${selectField('任务状态','status',[['todo','待开始'],['doing','进行中'],['blocked','遇到阻塞'],...(v.status==='done'?[['done','已完成']]:[]),...(v.status==='waived'?[['waived','掌握豁免']]:[])],v.status||'todo')}${field('单独改期（清空则跟随整体排期）','dueDate',v.dueDate||'','date')}</div>${area('任务笔记','notes',v.notes||'','maxlength="15000" placeholder="公式、报错、思路或验证结果…"')}${field('证据链接 · Git commit / W&B / 报告','evidence',v.evidence||'','url','maxlength="2047" placeholder="https://…"')}${area('阻塞原因 / 下一步','blocker',v.blocker||'','maxlength="3000" rows="2"')}<div class="dialog-actions">${button('补记用时','manual-session',id,'','clock')}${button('掌握豁免','waive',id)}<button class="btn" type="submit">保存笔记</button>${button(v.status==='done'?'重新打开':'完成此任务','complete-in-dialog',id,'primary','check')}</div></form><div class="row between mt-sm">${button('开始专注','start-focus',id,'sm','play')}${id.startsWith('custom-')?button('删除补充任务','delete-custom',id,'sm danger','trash'):'<span class="tiny muted">学习计时不会自动完成任务</span>'}</div>${v.status==='waived'?`<p class="small muted mt-sm">豁免理由：${esc(v.reason)}</p>`:''}`);}
async function saveTaskForm(form){if(!form.reportValidity())return false;const id=form.getAttribute('data-id'),t=findTask(id,store.state),f=new FormData(form),evidence=String(f.get('evidence')||'').trim(),due=String(f.get('dueDate')||'');if(evidence&&!safeUrl(evidence))throw Error('证据链接只允许 http(s)，且不能含用户名/密码。');if(due&&!validDate(due))throw Error('日期不合法');if(due&&store.state.settings.strict){const unfinished=(t.dependencies||[]).map(x=>findTask(x,store.state)).filter(p=>p&&!isFinished(p,store.state));if(unfinished.some(p=>taskDate(p,store.state)>due))throw Error('不能把任务排在尚未完成的前置任务之前。');}await store.mutate(s=>{const status=String(f.get('status'));if(status!==(s.tasks[id]?.status||'todo'))setTaskStatus(s,id,status,s.tasks[id]?.reason||'');s.tasks[id]={...s.tasks[id],notes:String(f.get('notes')||''),evidence,blocker:String(f.get('blocker')||''),updatedAt:Date.now()};if(due)s.tasks[id].dueDate=due;else delete s.tasks[id].dueDate;});dialogDirty=false;return true;}
async function toggleTask(id,fromDialog=false){if(fromDialog){const form=dialog.querySelector('form[data-form="task"]');if(form&&!(await saveTaskForm(form)))return;}const t=findTask(id,store.state);if(!t)return;const old=store.state.tasks[id]?.status,next=['done','waived'].includes(old)?'todo':'done';try{await store.mutate(s=>{setTaskStatus(s,id,next);if(next==='todo'&&id.endsWith('-verify'))for(let p=t.phase;p<phases.length;p++)s.gates[p]=false;});if(fromDialog)taskDialog(id);render();toast(next==='done'?'已完成。计划进度已更新；实际时长仍以记录为准。':'已重新打开。相关阶段验收需要重新确认。');}catch(e){if(!fromDialog)taskDialog(id);throw e;}}
function waiverDialog(id){const t=findTask(id,store.state);openDialog('记录掌握证据',`${notice('豁免用于已经掌握的内容。它能满足前置，但不会增加完成学时或实际用时。','warn')}<p class="small mb">${esc(t.title)}</p><form data-form="waive" data-id="${esc(id)}">${area('说明已掌握的证据或合理的范围调整','reason',store.state.tasks[id]?.reason||'','required minlength="4" maxlength="2000" placeholder="例如：已在项目中实现并测试过 PPO loss，代码见…"')}${formActions('确认掌握豁免')}</form>`);}
function newTaskDialog(){openDialog('添加补充任务',`${notice('补充任务不计入基础300小时进度，但会计入本日计划负荷与实际计时。')}<form data-form="new-task">${field('任务名称','title','','text','required maxlength="150" autofocus')}<div class="form-grid">${selectField('归属学习日','day',days.map(d=>[d.day,'D'+d.day+' · '+d.title]),ctx.selectedDay)}${field('计划分钟数','minutes',30,'number','required min="5" max="600" step="5"')}</div>${area('具体做什么','description','','required maxlength="8000"')}${area('怎样算完成','acceptance','','required maxlength="3000"')}${selectField('前置任务（可选）','dependency',[['','无前置'],...allTasks(store.state).map(t=>[t.id,'D'+t.day+' · '+t.title])],'')}${formActions('添加任务')}</form>`);}
function manualSession(id='',editId=''){const entry=store.state.sessions[editId]||{};openDialog(editId?'校正学习记录':'补记实际用时',`${notice('只填写实际投入时间。完成任务不会自动添加时间；请避免和已记录的专注重复。')}<form data-form="session" data-id="${esc(editId)}"><div class="form-grid">${field('日期','date',entry.date||dateKey(),'date','required')}${field('实际分钟数','minutes',entry.minutes||30,'number','required min="0.1" max="1440" step="0.1"')}</div>${selectField('关联任务','taskId',[['','自由学习 / 未关联'],...allTasks(store.state).map(t=>[t.id,'D'+t.day+' · '+t.title])],entry.taskId||id)}${area('说明','note',entry.note||'','maxlength="1000"')}${formActions('保存学习记录')}</form>`);}
function sessionsDialog(){const entries=Object.values(store.state.sessions).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);openDialog('实际学习记录',`<div class="row between mb"><p class="small muted">计时为墙钟；中途离开可在这里校正。</p>${button('手动补记','manual-session','','primary','plus')}</div>${entries.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>任务</th><th>时长</th><th>操作</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${e.date}</td><td title="${esc(e.note)}"><div class="title-cell">${esc(findTask(e.taskId,store.state)?.title||'自由学习')}</div><span class="tiny muted">${esc(e.kind==='timer'?'专注计时':'手动记录')}</span></td><td>${e.minutes} min</td><td>${button('校正','edit-session',e.id,'sm')}<button class="icon-button" data-action="delete-session" data-id="${esc(e.id)}" aria-label="删除这条学习记录">${icon('trash',14)}</button></td></tr>`).join('')}</tbody></table></div>`:empty('还没有实际用时','开始一轮专注，或补记已完成的学习时间。')}`);}
async function startTimer(taskId='',mode='focus'){if(store.state.timer){timerDialog();return;}if(mode==='focus'&&!taskId)taskId=allTasks(store.state).find(t=>t.day===ctx.selectedDay&&!isFinished(t,store.state))?.id||'';if(taskId&&!findTask(taskId,store.state))throw Error('任务已不存在');await store.mutate(s=>{if(s.timer)throw Error('另一窗口已经启动计时，请先管理当前一轮。');const duration=(mode==='focus'?s.settings.focusMinutes:s.settings.breakMinutes)*60000;s.timer={id:uid(),taskId:mode==='focus'?taskId:'',mode,durationMs:duration,remainingMs:duration,startedAt:Date.now(),date:dateKey(),status:'running'};recordEvent(s,'开始'+(mode==='focus'?'专注':'休息')+(taskId?'：'+findTask(taskId,s).title:''));});try{if(store.state.settings.sound){audioContext||=new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();}}catch{}if(dialog.open&&!dialogDirty)closeDialog(true);render();toast(mode==='focus'?'专注已开始。计时不等于任务验收。':'休息已开始，不计入学习时长。');}
function timerDialog(){const t=store.state.timer;openDialog('专注计时',`${notice('刷新或关闭后返回，会根据墙钟时间恢复。睡眠或离开也可能计入，请在学习记录中校正。','warn')}<div style="text-align:center"><div class="eyebrow">${t?t.mode==='focus'?'FOCUS SESSION':'TAKE A BREAK':'READY WHEN YOU ARE'}</div><div class="focus-clock mono" data-timer-clock>${clockText(t?timerRemaining(t):store.state.settings.focusMinutes*60000)}</div><p class="small muted mt-sm">${esc(t?findTask(t.taskId,store.state)?.title||(t.mode==='break'?'休息不计入学习时间':'自由专注'):'选择一个具体问题，完成一轮专注。')}</p><div class="row wrap mt" style="justify-content:center">${t?button(t.status==='running'?'暂停':'继续','pause-timer','','primary',t.status==='running'?'pause':'play')+button('结束并记录','stop-timer','','','check')+button('放弃本轮','discard-timer','','danger'):button('开始专注','start-focus','','primary','play')+button('休息一轮','start-break','','','clock')}</div></div><div class="divider"></div><div class="row between"><span class="small muted">计时只记用时，不自动完成任务。</span>${button('学习记录','sessions','','sm')}</div>`);}
async function pauseTimer(){await store.mutate(s=>{const t=s.timer;if(!t)return;if(t.status==='running'){t.remainingMs=timerRemaining(t);t.status='paused';}else{t.startedAt=Date.now();t.status='running';}});timerDialog();updateTimerUI();}
async function finishTimer(discard=false){if(discard&&!confirm('放弃本轮？本轮未结算的时间不会计入记录。'))return;await store.mutate(s=>{if(discard)s.timer=null;else settleTimer(s,{stop:true});});render();timerDialog();toast(discard?'本轮已放弃，未增加时长。':'本轮已结束，实际时间已记录（休息除外）。');}
function beep(){try{if(!store.state.settings.sound||!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=660;g.gain.value=.05;o.connect(g);g.connect(audioContext.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.35);o.stop(audioContext.currentTime+.36);}catch{}}
function updateTimerUI(){const t=store.state.timer,remain=t?timerRemaining(t):store.state.settings.focusMinutes*60000;$$('[data-timer-clock]').forEach(e=>e.textContent=clockText(remain));$$('[data-timer-progress]').forEach(e=>e.style.width=(t?100-remain/t.durationMs*100:0)+'%');$('#timer-float')?.classList.toggle('hidden',!t);}
setInterval(async()=>{updateTimerUI();const t=store.state.timer;if(t&&t.status==='running'&&timerRemaining(t)===0&&!settling){settling=true;let ended=false;try{await store.mutate(s=>{if(s.timer?.id===t.id)ended=settleTimer(s);});if(ended){beep();toast(t.mode==='focus'?'本轮专注已记录。休息一下，再验收产出。':'休息结束，准备下一轮。');if(ctx.view==='dashboard')render();if(dialog.open&&$('#dialog-title').textContent==='专注计时')timerDialog();}}catch(e){notifyError(e);}finally{settling=false;}}},1000);
function resourceNote(id){const r=resources.find(r=>r.id===id);openDialog(r.title,`${external(r.url,'打开原始资料','btn')}<p class="small muted mt">${esc(r.scope)}</p><form class="mt" data-form="resource" data-id="${id}">${area('阅读笔记 / 待查问题','notes',store.state.resources[id]?.notes||'','maxlength="15000"')}${formActions()}</form>`);}
function experimentDialog(id=''){const e=store.state.experiments[id]||{};openDialog(id?'实验记录 · '+e.name:'新建实验',`${notice('留空表示未测量，不会被当成0。名称、模型、数据划分和解码预算请尽量具体。')}<form data-form="experiment" data-id="${esc(id)}"><div class="form-grid">${field('实验名称','name',e.name,'text','required maxlength="150" autofocus')}${selectField('状态','status',[['planned','已计划'],['running','运行中'],['finished','已完成'],['failed','失败 / 中止']],e.status||'planned')}${field('模型 / checkpoint','model',e.model,'text','required maxlength="250"')}${field('算法 / 对照组','algorithm',e.algorithm,'text','required maxlength="150"')}${field('数据集 / manifest hash','dataset',e.dataset,'text','required maxlength="300"')}${field('划分 / 评测协议','split',e.split,'text','required maxlength="300"')}${field('随机种子','seed',e.seed,'text','maxlength="100"')}${field('GPU / 环境版本','gpu',e.gpu,'text','maxlength="250"')}${field('正确任务数','correct',e.correct,'number','min="0" step="1"')}${field('评测任务总数','total',e.total,'number','min="0" step="1"')}${field('平均 Reward（不能代替成功率）','reward',e.reward,'number','step="any"')}${field('平均工具交互步数','turns',e.turns,'number','min="0" step="any"')}${field('生成 token 总数','tokens',e.tokens,'number','min="0" step="1"')}${field('本次估计成本 · 元（不入总账）','cost',e.cost,'number','min="0" step="0.01"')}</div>${area('配置 / 预算 / reward 定义','config',e.config,'maxlength="15000" placeholder="LR, batch, G, length, KL, mask, total rollout tokens…"')}${field('W&B / 实验报告链接','url',e.url,'url','maxlength="2047"')}${field('代码 commit / 产物链接','commit',e.commit,'url','maxlength="2047"')}${area('观察、失败、混杂因素与局限','notes',e.notes,'maxlength="15000"')}${formActions('保存实验')}</form>`);}
function localDateTime(iso){if(!iso)return '';const d=new Date(iso);return dateKey(d)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
function expenseDialog(id=''){const e=store.state.expenses[id]||{};openDialog(id?'编辑费用':'登记算力费用',`<form data-form="expense" data-id="${esc(id)}"><div class="form-grid">${field('账单日期','date',e.date||dateKey(),'date','required')}${selectField('分类','category',['GPU','API','存储','其他'].map(x=>[x,x]),e.category||'GPU')}</div>${field('用途 / GPU / 实例标识（不要填写凭据）','label',e.label,'text','required maxlength="180" autofocus')}<div class="form-grid">${field('用量（小时、GB月或一笔账单填1）','quantity',e.quantity??1,'number','required min="0" max="100000" step="any"')}${field('实际单价 · 人民币','rate',e.rate??'','number','required min="0" max="1000000" step="any"')}</div><p class="small mb" id="expense-preview">预计记账：${money(e.amount||0)}</p>${field('可选：希望提醒你关机的本地时间','stopAt',localDateTime(e.stopAt),'datetime-local')}<label class="row small mb"><input type="checkbox" name="closed" ${e.closed?'checked':''}>我已在云控制台确认停机</label>${area('备注','note',e.note,'maxlength="3000"')}${notice('此提醒不连接云平台、不监控实例，也不会自动关机。单价若为外币，请先按账单换成人民币。','warn')}${formActions('保存到账本')}</form>`);}
function milestoneDialog(id){const m=milestones.find(m=>m.id===id),v=store.state.milestones[id]||{};openDialog(m.title,`<p class="small muted mb">D${m.day} 目标 · ${esc(m.detail)}</p><form data-form="milestone" data-id="${id}">${field(m.evidence,'link',v.link||'','url','maxlength="2047" placeholder="https://…"')}${area('证据说明 / 未完成项','notes',v.notes||'','maxlength="8000"')}<label class="row small mt"><input type="checkbox" name="done" ${v.done?'checked':''}>我已验收产物，可以对外说明其范围和局限</label>${formActions('保存里程碑')}</form>`);}
function queueJournal(field,value){if(!Object.keys(pendingJournal).length)journalDay=ctx.selectedDay;pendingJournal[field]=value;clearTimeout(journalTimer);if($('#journal-save'))$('#journal-save').textContent='正在保存…';journalTimer=setTimeout(()=>flushJournal().catch(notifyError),550);}
async function flushJournal(){clearTimeout(journalTimer);if(!Object.keys(pendingJournal).length)return;const patch={...pendingJournal},day=journalDay;pendingJournal={};try{await store.mutate(s=>{s.journals[day]={...s.journals[day],...patch,updatedAt:Date.now()};});if($('#journal-save'))$('#journal-save').textContent=store.mode==='memory'?'仅内存 · 请导出备份':'已保存 · '+new Date().toLocaleTimeString('zh-CN');}catch(e){pendingJournal={...patch,...pendingJournal};if($('#journal-save'))$('#journal-save').textContent='保存失败，文本仍在页面中，请复制或导出。';throw e;}}
function journalMarkdown(day){const d=days[day-1],v=store.state.journals[day]||{};return `# D${day} · ${d.title}\n\n`+[['notes','研究正文'],['learned','理解'],['blocker','阻塞'],['hypothesis','假设'],['next','下一步']].map(([k,t])=>'## '+t+'\n\n'+(v[k]||'（未填写）')+'\n').join('\n');}
async function exportBackup(encrypted=false,password=''){await flushJournal();await store.mutate(s=>{s.settings.lastBackup=Date.now();});const text=JSON.stringify(backupEnvelope(store.state),null,2);if(encrypted){const payload=await encrypt(text,password);download('rlmc-backup-'+dateKey()+'.rlmc',JSON.stringify(payload),'application/json');}else download('rlmc-backup-'+dateKey()+'.json',text,'application/json');toast('已触发备份下载。请确认文件已保存到独立位置。');if(ctx.view==='settings')render();}
const toB64=bytes=>{let out='';for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out);};
function fromB64(s){if(typeof s!=='string'||s.length>12000000)throw Error('加密备份过大');return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function cryptoKey(password,salt){if(!crypto.subtle)throw Error('此环境不支持加密，请使用 HTTPS 或 localhost。');const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encrypt(text,password){if(password.length<8)throw Error('密码至少8个字符，请使用独特的长密码。');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await cryptoKey(password,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(text));return {format:'rlmc-encrypted',version:1,iterations:600000,salt:toB64(salt),iv:toB64(iv),data:toB64(new Uint8Array(cipher))};}
async function decrypt(raw,password){if(raw.version!==1||raw.iterations!==600000)throw Error('不支持的加密备份版本');try{const salt=fromB64(raw.salt),iv=fromB64(raw.iv);if(salt.length!==16||iv.length!==12)throw Error('invalid');const key=await cryptoKey(password,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,fromB64(raw.data));return new TextDecoder().decode(plain);}catch{throw Error('密码不正确，或加密文件已损坏。当前数据未改变。');}}
function encryptedExportDialog(){openDialog('加密备份',`${notice('使用 AES-GCM 加密，密码只用于当前导出，不保存。忘记密码无法恢复；请妥善保管。','warn')}<form data-form="encrypted-export">${field('备份密码（至少8个字符）','password','','password','required minlength="8" maxlength="200" autocomplete="new-password" autofocus')}${field('再次输入','confirm','','password','required minlength="8" maxlength="200" autocomplete="new-password"')}${formActions('加密并下载')}</form>`);}
async function importFile(file){if(!file)return;if(file.size>12000000)throw Error('文件超过12MB限制');const text=await file.text();let raw;try{raw=JSON.parse(text);}catch{throw Error('文件不是有效 JSON');}if(raw.format==='rlmc-encrypted'){encryptedCandidate=raw;openDialog('解密备份',`<form data-form="decrypt">${field('备份密码','password','','password','required maxlength="200" autofocus autocomplete="off"')}${formActions('解密并预览')}</form>`);}else previewImport(parseBackup(text));}
function previewImport(data){validateState(data);importCandidate=clone(data);const st=stats(data);openDialog('恢复前预览',`${notice('这是完整替换，不是合并。当前数据会先保留为本地快照；进行中的计时不会随备份恢复。请确认备份来自你自己。','warn')}<div class="stat-inline"><div><small>完成任务</small><b>${st.done}</b></div><div><small>实际学习</small><b>${hours(st.actual)} h</b></div><div><small>已入账</small><b>${money(st.spent)}</b></div></div><p class="small muted">开始日：${data.settings.startDate} · 修订 ${data.revision} · 课程 ${esc(data.planVersion)}</p><div class="dialog-actions">${button('取消','close')}${button('确认替换并恢复','confirm-import','','primary','refresh')}</div>`);}
async function snapshotsDialog(){const list=await store.snapshotList();ctx.snapshots=list;openDialog('本地恢复快照',`${notice('每20次数据变更以及导入/重置前保留快照，最多7份（降级模式5份）。它们与主数据同在此浏览器，不是独立备份。')}<div class="stack">${list.map((x,i)=>`<div class="panel pad row between"><div><h3>${fmtTime(x.at)}</h3><p class="small muted">修订 ${x.revision} · 恢复会先预览</p></div>${button('预览','snapshot',String(i),'sm')}</div>`).join('')||empty('暂无快照','开始使用后自动生成；现在可以先导出一份 JSON。')}</div>`);}
async function storageInfo(){const el=$('#storage-capacity');if(!el)return;try{const persisted=await navigator.storage?.persisted?.(),estimate=await navigator.storage?.estimate?.();if($('#storage-capacity'))$('#storage-capacity').textContent=(persisted?'浏览器已授予持久存储':'尚未授予持久存储（不影响常规保存）')+(estimate?.usage?' · 本站占用约 '+(estimate.usage/1048576).toFixed(1)+'MB':'');}catch{if($('#storage-capacity'))$('#storage-capacity').textContent='浏览器未提供配额信息，请定期独立备份。';}}
function updateNetwork(){if($('#network-state'))$('#network-state').textContent=navigator.onLine?'':'离线模式';}
function globalSearch(){openDialog('搜索工作台',`<div class="search-input">${icon('search',17)}<input id="global-search" placeholder="搜索任务、论文、知识点…" autocomplete="off" autofocus aria-label="全局搜索"></div><div class="search-results" id="search-results"><p class="small muted">输入关键词。搜索覆盖课程任务、资料和概念卡，不上传查询内容。</p></div>`);}
function searchResults(q){q=q.trim().toLowerCase();if(!q){$('#search-results').innerHTML='<p class="small muted">输入关键词开始搜索。</p>';return;}const hits=[...allTasks(store.state).filter(t=>(t.title+' '+t.description).toLowerCase().includes(q)).map(t=>({action:'task',id:t.id,title:t.title,meta:'任务 · D'+t.day+' · '+t.minutes+'min'})),...resources.filter(r=>(r.title+' '+r.scope).toLowerCase().includes(q)).map(r=>({action:'resource-note',id:r.id,title:r.title,meta:'资料 · '+r.type})),...days.filter(d=>(d.question+' '+d.answer).toLowerCase().includes(q)).map(d=>({action:'search-review',id:d.day,title:d.question,meta:'自测 · D'+d.day}))].slice(0,45);$('#search-results').innerHTML=hits.map(h=>`<button class="search-result" data-action="${h.action}" data-id="${esc(h.id)}">${esc(h.title)}<small>${esc(h.meta)}</small></button>`).join('')||'<p class="small muted">没有结果。尝试 GRPO、mask、预算或 LoRA。</p>';}
async function handleAction(action,id,el){
 if(navs.some(n=>n[0]===action)){if(dialog.open)closeDialog();if(dialog.open)return;await navigate(action);return;}
 switch(action){
 case 'close':closeDialog();break;
 case 'menu':menu(!$('.sidebar').classList.contains('open'));break;
 case 'menu-close':menu(false);break;
 case 'theme':await store.mutate(s=>{s.settings.theme=s.settings.theme==='dark'?'light':'dark';});render();break;
 case 'select-day':await flushJournal();ctx.selectedDay=Number(id);render();if(ctx.view==='plan')$('#selected-day-plan')?.scrollIntoView({behavior:'smooth',block:'start'});break;
 case 'go-day':ctx.selectedDay=Number(id);await navigate('dashboard');break;
 case 'plan-mode':ctx.planMode=id;render();break;
 case 'overdue':ctx.planMode='overdue';await navigate('plan');break;
 case 'task':taskDialog(id);break;
 case 'toggle-task':await toggleTask(id);break;
 case 'complete-in-dialog':await toggleTask(id,true);break;
 case 'waive':if(dialogDirty){const f=dialog.querySelector('form[data-form="task"]');if(f&&!(await saveTaskForm(f)))return;}waiverDialog(id);break;
 case 'new-task':newTaskDialog();break;
 case 'delete-custom':if(confirm('删除这个补充任务？历史学习时间仍保留。')){await store.mutate(s=>{s.customTasks[id].deleted=true;recordEvent(s,'删除补充任务');},{snapshot:true});closeDialog(true);render();}break;
 case 'gate':{const p=phases[Number(id)];await store.mutate(s=>{if(s.gates[p.id]){for(let i=p.id;i<phases.length;i++)s.gates[i]=false;recordEvent(s,'撤销阶段验收：'+p.name);}else{const missing=tasks.filter(t=>t.phase===p.id&&t.id.endsWith('-verify')&&!isFinished(t,s));if(missing.length)throw Error('请先完成或合理豁免本阶段的实验验收：'+missing.map(t=>'D'+t.day).join('、'));s.gates[p.id]=true;recordEvent(s,'阶段验收：'+p.name);}});render();toast('阶段验收已更新。');break;}
 case 'carry':{const list=allTasks(store.state).filter(t=>!isFinished(t,store.state)&&taskDate(t,store.state)<dateKey()),next=nextStudyDate(store.state);if(!list.length)return;if(confirm(`将 ${list.length} 个逾期任务改到 ${next}？原学习日归属不变，也不会绕过前置；当日可能超过10小时，请分批执行。`)){await store.mutate(s=>{list.forEach(t=>{s.tasks[t.id]={...s.tasks[t.id],dueDate:next};});recordEvent(s,`结转 ${list.length} 项任务到 ${next}`);},{snapshot:true});render();}break;}
 case 'manual-session':if(dialogDirty){const f=dialog.querySelector('form[data-form="task"]');if(f&&!(await saveTaskForm(f)))return;}manualSession(id);break;
 case 'edit-session':manualSession('',id);break;
 case 'sessions':sessionsDialog();break;
 case 'delete-session':if(confirm('删除这条实际用时记录？')){await store.mutate(s=>{delete s.sessions[id];});render();sessionsDialog();}break;
 case 'start-focus':await startTimer(id);break;
 case 'start-break':await startTimer('','break');break;
 case 'timer':timerDialog();break;
 case 'pause-timer':await pauseTimer();break;
 case 'stop-timer':await finishTimer();break;
 case 'discard-timer':await finishTimer(true);break;
 case 'star-resource':await store.mutate(s=>{s.resources[id]={...s.resources[id],star:!s.resources[id]?.star};});render();break;
 case 'resource-state':await store.mutate(s=>{s.resources[id]={...s.resources[id],status:((s.resources[id]?.status||0)+1)%3};});render();break;
 case 'resource-note':resourceNote(id);break;
 case 'review-mode':ctx.reviewMode=id;render();break;
 case 'grade-review':{const [card,grade]=id.split(':');await store.mutate(s=>gradeReview(s,card,grade));render();toast('已安排下次复习：'+store.state.reviews[card].due);break;}
 case 'new-experiment':experimentDialog();break;
 case 'edit-experiment':experimentDialog(id);break;
 case 'delete-experiment':if(confirm('删除此实验记录？可先导出备份。')){await store.mutate(s=>{delete s.experiments[id];},{snapshot:true});ctx.compare=ctx.compare.filter(x=>x!==id);render();}break;
 case 'clear-compare':ctx.compare=[];render();break;
 case 'new-expense':expenseDialog();break;
 case 'edit-expense':expenseDialog(id);break;
 case 'delete-expense':if(confirm('删除此费用记录？总账将同时减少。')){await store.mutate(s=>{delete s.expenses[id];},{snapshot:true});render();}break;
 case 'close-instance':if(confirm('请先到云控制台确认实例已经停止。现在标记为已确认停机？')){await store.mutate(s=>{s.expenses[id].closed=true;recordEvent(s,'确认停机：'+s.expenses[id].label);});render();}break;
 case 'milestone':milestoneDialog(id);break;
 case 'export':await exportBackup();break;
 case 'encrypt-export':encryptedExportDialog();break;
 case 'import':$('#import-file').value='';$('#import-file').click();break;
 case 'confirm-import':if(!importCandidate)throw Error('没有待恢复的备份');await flushJournal();await store.replace(importCandidate);ctx.selectedDay=1;ctx.compare=[];importCandidate=null;closeDialog(true);render();toast('已恢复。原数据已先保留在本地快照。');break;
 case 'snapshots':await snapshotsDialog();break;
 case 'snapshot':previewImport(ctx.snapshots[Number(id)].state);break;
 case 'persist':{const granted=await navigator.storage?.persist?.();await storageInfo();toast(granted?'浏览器已授予持久存储；仍建议独立备份。':'浏览器未授予持久存储。常规保存仍可用，请定期导出。');break;}
 case 'reset':openDialog('重置本地工作台',`${notice('此操作会清空进度、笔记、实验、账本和设置。会保留一份本地快照，但请先下载独立备份。','warn')}<form data-form="reset">${field('输入 RESET 确认','confirm','','text','required pattern="RESET" autocomplete="off"')}${formActions('确认重置')}</form>`);break;
 case 'export-plan':download('30-day-300h-plan.md',planMarkdown(store.state),'text/markdown;charset=utf-8');toast('完整30天课程已导出。');break;
 case 'export-ics':download('rl-research-plan.ics',calendarICS(store.state),'text/calendar;charset=utf-8');toast('已导出30个全天学习日；单项改期以工作台为准。');break;
 case 'export-journal':await flushJournal();download(`research-day${id}.md`,journalMarkdown(Number(id)),'text/markdown;charset=utf-8');break;
 case 'export-all-journals':await flushJournal();download('research-journal.md',days.map(d=>journalMarkdown(d.day)).join('\n---\n\n'),'text/markdown;charset=utf-8');break;
 case 'weekly-summary':await flushJournal();openDialog('基于真实记录的周复盘',`<pre class="code-block">${esc(weeklySummary(store.state,Number(id)))}</pre><div class="dialog-actions">${button('下载复盘','export-week',id,'primary','download')}</div>`);break;
 case 'export-week':download(`week-from-day${id}.md`,weeklySummary(store.state,Number(id)),'text/markdown;charset=utf-8');break;
 case 'export-experiments':{const cols=['name','model','algorithm','dataset','split','seed','gpu','status','correct','total','reward','turns','tokens','cost','config','url','commit','notes'];download('experiments.csv',csv([cols,...Object.values(store.state.experiments).map(e=>cols.map(k=>e[k]))]),'text/csv;charset=utf-8');break;}
 case 'export-expenses':{const cols=['date','label','category','quantity','rate','amount','stopAt','closed','note'];download('expenses.csv',csv([cols,...Object.values(store.state.expenses).map(e=>cols.map(k=>e[k]))]),'text/csv;charset=utf-8');break;}
 case 'export-sessions':download('study-sessions.csv',csv([['date','task','minutes','kind','note'],...Object.values(store.state.sessions).map(e=>[e.date,findTask(e.taskId,store.state)?.title||'自由学习',e.minutes,e.kind,e.note])]),'text/csv;charset=utf-8');break;
 case 'export-portfolio':download('portfolio.md','# 研究作品索引\n\n'+milestones.map(m=>{const v=store.state.milestones[m.id]||{};return `## ${v.done?'[x]':'[ ]'} ${m.title}\n\n${m.detail}\n\n证据：${v.link||'未填写'}\n\n${v.notes||''}\n`;}).join('\n'),'text/markdown;charset=utf-8');break;
 case 'search':globalSearch();break;
 case 'search-review':{const d=days[Number(id)-1];openDialog('D'+id+' 概念自测',`<h3>${esc(d.question)}</h3><details class="guide-section mt"><summary>展开参考要点</summary><p>${esc(d.answer)}</p></details>`);break;}
 case 'copy-setup':{const text=$('.code-block')?.textContent;if(!navigator.clipboard)throw Error('此浏览器不支持自动复制，请手动选中命令。');await navigator.clipboard.writeText(text);toast('命令已复制。请先阅读注释，确认本机条件。');break;}
 case 'install':if(installPrompt){await installPrompt.prompt();installPrompt=null;}else openDialog('离线与安装',`<p class="small muted">通过 HTTPS 或 localhost 首次打开后，应用会缓存自身页面和代码。外部论文不在离线缓存中。</p><div class="divider"></div><p class="small muted">Chrome / Edge 若显示安装图标，可安装为应用；Safari 可使用“添加到主屏幕”或浏览器菜单。是否提供安装入口由浏览器决定。请勿把隐私模式当成长期数据存储。</p><div class="divider"></div>${notice('本机数据不自动跨设备同步。换电脑前导出 JSON；更换站点地址后也需要导入。','warn')}`);break;
 case 'raw-recovery':download('rlmc-raw-recovery.json',JSON.stringify(await store.rawRecovery(),null,2),'application/json');break;
 case 'reload':location.reload();break;
 default:throw Error('未知操作：'+action);
 }
}
async function submitForm(form){
 if(!form.reportValidity())return;
 // Named form controls (for example name="dataset") can shadow form.dataset.
 // Read metadata through attributes, never through the form's named properties.
 const kind=form.getAttribute('data-form'),id=form.getAttribute('data-id')||'',f=new FormData(form),get=k=>String(f.get(k)||'').trim(),num=k=>get(k)===''?null:Number(get(k));
 if(kind==='task'){if(await saveTaskForm(form)){toast('任务笔记已保存。');render();}return;}
 if(kind==='settings'){const weekdays=f.getAll('weekdays').map(Number),rests=get('restDates').split(/[\s,，]+/).filter(Boolean);if(!weekdays.length)throw Error('至少选择一个学习日。');if(!rests.every(validDate))throw Error('休息日请使用 YYYY-MM-DD，每行一个。');await store.mutate(s=>{s.settings={...s.settings,name:get('name'),startDate:get('startDate'),budget:num('budget'),theme:get('theme'),focusMinutes:num('focusMinutes'),breakMinutes:num('breakMinutes'),weekdays,restDates:[...new Set(rests)],strict:f.has('strict'),sound:f.has('sound'),onboarded:true};planDates(s);recordEvent(s,'更新排期与工作台设置');});render();toast('设置已保存。单独改期的任务仍保留其日期。');return;}
 if(kind==='waive'){await store.mutate(s=>setTaskStatus(s,id,'waived',get('reason')));closeDialog(true);render();toast('已记录掌握豁免，不增加完成学时。');return;}
 if(kind==='new-task'){const day=num('day'),d=days[day-1],taskId='custom-'+uid();await store.mutate(s=>{s.customTasks[taskId]={id:taskId,day,phase:d.phase,title:get('title'),description:get('description'),acceptance:get('acceptance'),minutes:num('minutes'),kind:'补充',time:'额外计划',resources:[],dependencies:get('dependency')?[get('dependency')]:[],createdAt:Date.now()};recordEvent(s,'添加补充任务：'+get('title'));});ctx.selectedDay=day;closeDialog(true);render();return;}
 if(kind==='session'){const sid=id||'manual-'+uid(),date=get('date'),minutes=num('minutes');await store.mutate(s=>{const total=Object.values(s.sessions).filter(x=>x.date===date&&x.id!==sid).reduce((a,x)=>a+x.minutes,0);if(total+minutes>1440)throw Error('同一日期的记录不能超过24小时，请检查重复计时。');s.sessions[sid]={id:sid,date,minutes,taskId:get('taskId'),kind:id?s.sessions[id].kind:'manual',note:get('note'),createdAt:id?s.sessions[id].createdAt:Date.now()};recordEvent(s,'记录学习 '+minutes+' 分钟');});closeDialog(true);render();toast('实际用时已保存。');return;}
 if(kind==='resource'){await store.mutate(s=>{s.resources[id]={...s.resources[id],notes:get('notes')};});closeDialog(true);render();return;}
 if(kind==='experiment'){for(const k of ['url','commit'])if(get(k)&&!safeUrl(get(k)))throw Error('链接必须是安全的 http(s) 地址。');const eid=id||uid();await store.mutate(s=>{const e={id:eid,createdAt:s.experiments[eid]?.createdAt||Date.now(),updatedAt:Date.now()};for(const k of ['name','status','model','algorithm','dataset','split','seed','gpu','config','url','commit','notes'])e[k]=get(k);for(const k of ['correct','total','reward','turns','tokens','cost'])e[k]=num(k);s.experiments[eid]=e;recordEvent(s,'记录实验：'+e.name);});closeDialog(true);render();toast('实验已保存，未测量的指标保持空白。');return;}
 if(kind==='expense'){const eid=id||uid(),quantity=num('quantity'),rate=num('rate');await store.mutate(s=>{s.expenses[eid]={id:eid,date:get('date'),label:get('label'),category:get('category'),quantity,rate,amount:Math.round(quantity*rate*100)/100,stopAt:get('stopAt')?new Date(get('stopAt')).toISOString():'',closed:f.has('closed'),note:get('note'),createdAt:s.expenses[eid]?.createdAt||Date.now()};recordEvent(s,'记账 '+money(quantity*rate)+'：'+get('label'));});closeDialog(true);render();return;}
 if(kind==='milestone'){if(get('link')&&!safeUrl(get('link')))throw Error('证据链接必须是 http(s) 地址。');if(f.has('done')&&!get('link')&&!get('notes'))throw Error('验收时至少填写证据链接或具体的产物说明。');await store.mutate(s=>{s.milestones[id]={done:f.has('done'),link:get('link'),notes:get('notes'),updatedAt:Date.now()};recordEvent(s,'更新作品里程碑：'+milestones.find(m=>m.id===id).title);});closeDialog(true);render();return;}
 if(kind==='encrypted-export'){const password=String(f.get('password'));if(password!==String(f.get('confirm')))throw Error('两次密码不一致。');const submit=form.querySelector('[type=submit]');submit.disabled=true;submit.textContent='正在加密…';try{await exportBackup(true,password);closeDialog(true);}finally{submit.disabled=false;submit.textContent='加密并下载';}return;}
 if(kind==='decrypt'){if(!encryptedCandidate)throw Error('没有加密文件');const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const text=await decrypt(encryptedCandidate,String(f.get('password')));encryptedCandidate=null;previewImport(parseBackup(text));}finally{submit.disabled=false;}return;}
 if(kind==='reset'){if(get('confirm')!=='RESET')throw Error('请输入 RESET 确认。');await store.replace(initialState());ctx.selectedDay=1;ctx.compare=[];closeDialog(true);render();toast('已重置。原数据保留在本地恢复快照中。');return;}
 throw Error('未识别的表单');
}
// Delegated actions preserve native keyboard behavior and avoid inline event handlers.
document.addEventListener('click',event=>{const nav=event.target.closest('a[href^="#"]');if(nav&&nav.getAttribute('href')!=='#main'){event.preventDefault();navigate(nav.hash.slice(1)).catch(notifyError);return;}const target=event.target.closest('[data-action]');if(target){event.preventDefault();handleAction(target.dataset.action,target.dataset.id||'',target).catch(notifyError);}});
document.addEventListener('submit',event=>{const form=event.target.closest('form[data-form]');if(!form)return;event.preventDefault();submitForm(form).catch(notifyError);});
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.journal){queueJournal(el.dataset.journal,el.value);return;}if(el.id==='global-search'){searchResults(el.value);return;}if(el.dataset.filter==='resource-query'){ctx.resourceQuery=el.value;render();return;}if(dialog.contains(el)&&el.closest('form'))dialogDirty=true;if(el.closest('form[data-form="expense"]')&&['quantity','rate'].includes(el.name)){const form=el.form;$('#expense-preview').textContent='预计记账：'+money(Number(form.elements.quantity.value)*Number(form.elements.rate.value));}});
document.addEventListener('change',event=>{const el=event.target;if(dialog.contains(el)&&el.closest('form'))dialogDirty=true;if(el.id==='import-file'){importFile(el.files[0]).catch(notifyError);return;}switch(el.dataset.filter){case 'resource-type':ctx.resourceType=el.value;render();break;case 'resource-status':ctx.resourceStatus=el.value;render();break;case 'compare':if(el.checked){if(ctx.compare.length>=2){el.checked=false;toast('一次选择两条实验进行比较。');return;}ctx.compare.push(el.dataset.id);}else ctx.compare=ctx.compare.filter(id=>id!==el.dataset.id);render();break;}});
dialog.addEventListener('cancel',e=>{if(dialogDirty&&!confirm('还有未保存内容，确认关闭吗？'))e.preventDefault();else dialogDirty=false;});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
window.addEventListener('keydown',e=>{const editing=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!dialogDirty)globalSearch();return;}if(editing||dialog.open||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='/'){e.preventDefault();globalSearch();}else if(e.key==='1')navigate('dashboard').catch(notifyError);else if(e.key==='2')navigate('plan').catch(notifyError);else if(e.key==='?')openDialog('键盘快捷键','<div class="stack"><p><kbd>⌘ / Ctrl K</kbd> 或 <kbd>/</kbd> 搜索任务与资料</p><p><kbd>1</kbd> 总览　<kbd>2</kbd> 计划</p><p><kbd>Tab</kbd> 移动焦点　<kbd>Enter</kbd> 激活按钮</p><p><kbd>Esc</kbd> 关闭弹窗（未保存时提示）</p></div>');});
window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'dashboard').catch(notifyError));
window.addEventListener('beforeunload',e=>{if(Object.keys(pendingJournal).length||dialogDirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)flushJournal().catch(()=>{});else store.reload().then(()=>{updateTimerUI();updateStatus();}).catch(notifyError);});
window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
store.onChange=({external:remote})=>{updateStatus();updateTimerUI();if(remote){if(!dialog.open&&!Object.keys(pendingJournal).length&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))render();else toast('另一窗口已更新数据。当前表单内容保留；保存时仅写入此表单字段。');}};
async function boot(){try{await store.open();ctx.state=store.state;ctx.view=navs.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'dashboard';const dates=planDates(store.state),today=dateKey();ctx.selectedDay=Number(Object.keys(dates).find(d=>dates[d]===today))||allTasks(store.state).find(t=>!isFinished(t,store.state))?.day||30;$('#app').innerHTML=shell(ctx);render();if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))navigator.serviceWorker.register('./sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('应用有新版本。备份后关闭所有工作台窗口，再重新打开。');});});}).catch(()=>toast('离线缓存未启用，在线使用和本地保存仍可用。'));}catch(e){$('#app').innerHTML=`<div class="boot"><div class="boot-logo">RL</div><h1>数据需要安全恢复</h1><p>${esc(e.message)}</p><p class="muted small">没有自动覆盖现有数据。先导出原始记录，再尝试导入已知良好备份。</p><div class="row wrap">${button('导出原始恢复数据','raw-recovery','','primary','download')}${button('导入备份','import','','','upload')}${button('重新加载','reload','','','refresh')}</div></div>`;}}
boot();
