import {tasks,days,phases,resources,PLAN_VERSION} from './plan.js';
export const SCHEMA_VERSION=1;
export const clone=x=>JSON.parse(JSON.stringify(x));
export const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
export function dateKey(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
export function addDays(s,n){if(!validDate(s))throw Error('日期无效');const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export function dayDistance(a,b){return Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000);}
export function initialState(){return {schemaVersion:SCHEMA_VERSION,planVersion:PLAN_VERSION,revision:0,updatedAt:0,settings:{name:'研究者',startDate:dateKey(),theme:'light',budget:3500,focusMinutes:50,breakMinutes:10,weekdays:[0,1,2,3,4,5,6],restDates:[],strict:true,sound:false,onboarded:false,lastBackup:null},tasks:{},customTasks:{},journals:{},resources:{},reviews:{},gates:{},milestones:{},sessions:{},experiments:{},expenses:{},timer:null,events:[]};}
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeUrl(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password&&s.length<2048?u.href:'';}catch{return '';}}
export function allTasks(s){return [...tasks,...Object.values(s.customTasks)].filter(t=>!t.deleted);}
export function findTask(id,s){return tasks.find(t=>t.id===id)||s.customTasks[id];}
export const isFinished=(t,s)=>['done','waived'].includes(s.tasks[t.id]?.status);
export function planDates(s){let at=s.settings.startDate;const out={};for(let n=1,guard=0;n<=30&&guard<4000;guard++,at=addDays(at,1)){if(s.settings.weekdays.includes(new Date(at+'T12:00:00Z').getUTCDay())&&!s.settings.restDates.includes(at)){out[n++]=at;}}if(!out[30])throw Error('休息日过多，无法生成日程');return out;}
export function taskDate(t,s,dates=planDates(s)){return s.tasks[t.id]?.dueDate||dates[t.day];}
export function nextStudyDate(s,from=dateKey()){for(let i=1;i<4000;i++){const d=addDays(from,i);if(s.settings.weekdays.includes(new Date(d+'T12:00:00Z').getUTCDay())&&!s.settings.restDates.includes(d))return d;}throw Error('找不到下一学习日');}
export function blockers(t,s){const out=(t.dependencies||[]).filter(id=>{const p=findTask(id,s);return !p||!isFinished(p,s);}).map(id=>({id,label:findTask(id,s)?.title||id}));if(t.phase>0&&!s.gates[t.phase-1])out.push({id:'gate-'+(t.phase-1),label:phases[t.phase-1].name+' · 阶段验收'});return out;}
export function stats(s){const done=tasks.filter(t=>s.tasks[t.id]?.status==='done'),waived=tasks.filter(t=>s.tasks[t.id]?.status==='waived'),sessions=Object.values(s.sessions),spent=Object.values(s.expenses).reduce((a,e)=>a+e.amount,0);return {done:done.length,waived:waived.length,earned:done.reduce((a,t)=>a+t.minutes,0),covered:[...done,...waived].reduce((a,t)=>a+t.minutes,0),actual:sessions.reduce((a,x)=>a+x.minutes,0),todayActual:sessions.filter(x=>x.date===dateKey()).reduce((a,x)=>a+x.minutes,0),spent:Math.round(spent*100)/100,total:18000};}
export function dayStats(day,s){const list=allTasks(s).filter(t=>t.day===day);return {total:list.reduce((a,t)=>a+t.minutes,0),done:list.filter(t=>isFinished(t,s)).length,earned:list.filter(t=>s.tasks[t.id]?.status==='done').reduce((a,t)=>a+t.minutes,0),count:list.length};}
export function streak(s,today=dateKey()){const active=new Set(Object.values(s.sessions).filter(x=>x.minutes>0).map(x=>x.date));Object.values(s.tasks).filter(x=>x.status==='done'&&x.completedAt).forEach(x=>active.add(dateKey(new Date(x.completedAt))));let at=active.has(today)?today:addDays(today,-1),count=0;while(active.has(at)&&count<4000){count++;at=addDays(at,-1);}return count;}
export function recordEvent(s,text){s.events.unshift({id:uid(),at:Date.now(),text});s.events=s.events.slice(0,150);}
export function setTaskStatus(s,id,status,reason=''){const t=findTask(id,s);if(!t)throw Error('任务不存在');if(status==='done'&&s.settings.strict&&blockers(t,s).length)throw Error('请先完成前置任务和阶段验收，或记录已掌握理由后豁免。');if(status==='waived'&&reason.trim().length<4)throw Error('请用至少四个字说明掌握证据或豁免原因。');s.tasks[id]={...s.tasks[id],status,reason:status==='waived'?reason:(s.tasks[id]?.reason||''),completedAt:['done','waived'].includes(status)?Date.now():null,updatedAt:Date.now()};recordEvent(s,(status==='done'?'完成':status==='waived'?'掌握豁免':status==='blocked'?'标记阻塞':'更新')+'：'+t.title);}
export function timerRemaining(t,now=Date.now()){if(!t)return 0;return Math.max(0,t.remainingMs-(t.status==='running'?Math.max(0,now-t.startedAt):0));}
export function settleTimer(s,{stop=false,now=Date.now()}={}){const t=s.timer;if(!t)return false;const remain=timerRemaining(t,now);if(!stop&&(t.status!=='running'||remain>0))return false;const minutes=Math.round((t.durationMs-remain)/6000)/10;if(t.mode==='focus'&&minutes>0&&!s.sessions['timer-'+t.id])s.sessions['timer-'+t.id]={id:'timer-'+t.id,taskId:t.taskId||'',date:t.date,minutes,kind:'timer',note:'专注计时（墙钟时间，可在记录中校正）',createdAt:now};recordEvent(s,(t.mode==='focus'?'专注':'休息')+(stop?'已结束':'已完成'));s.timer=null;return true;}
export function gradeReview(s,id,grade,today=dateKey()){const old=s.reviews[id]||{interval:0,reps:0};const interval=grade==='again'?1:grade==='hard'?Math.max(1,Math.round((old.interval||1)*1.2)):grade==='good'?Math.min(60,old.interval?Math.round(old.interval*2):3):Math.min(90,old.interval?Math.round(old.interval*3):7);s.reviews[id]={interval,reps:old.reps+1,grade,due:addDays(today,interval),updatedAt:Date.now()};}
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const finite=(n,min=0,max=1e9)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
export function validateState(s){
 if(!object(s)||s.schemaVersion!==1)throw Error('不支持的备份版本，未覆盖当前数据。');
 let nodes=0;function walk(v,depth=0){if(++nodes>100000||depth>16)throw Error('备份结构过大');if(typeof v==='string'&&v.length>200000)throw Error('文本过长');if(typeof v==='number'&&!Number.isFinite(v))throw Error('非法数值');if(object(v)||Array.isArray(v))for(const [k,x]of Object.entries(v)){if(['__proto__','prototype','constructor'].includes(k))throw Error('危险字段');walk(x,depth+1);}}walk(s);
 const base=initialState();for(const k of Object.keys(s))if(!(k in base))throw Error('未知顶层字段：'+k);
 for(const key of ['tasks','customTasks','journals','resources','reviews','gates','milestones','sessions','experiments','expenses']){if(!object(s[key])||Object.keys(s[key]).length>10000)throw Error('无效数据区：'+key);}
 const a=s.settings;if(!object(a)||!validDate(a.startDate)||!finite(a.budget,1,1000000)||!['light','dark'].includes(a.theme)||!finite(a.focusMinutes,1,180)||!finite(a.breakMinutes,1,60)||typeof a.strict!=='boolean')throw Error('无效设置');
 if(!Array.isArray(a.weekdays)||!a.weekdays.length||!a.weekdays.every(x=>Number.isInteger(x)&&x>=0&&x<=6)||!Array.isArray(a.restDates)||a.restDates.length>1000||!a.restDates.every(validDate))throw Error('无效工作日配置');
 if(typeof a.name!=='string'||a.name.length>80||!finite(s.revision,0,1e12)||!finite(s.updatedAt,0,1e16)||!Array.isArray(s.events)||s.events.length>1000)throw Error('无效元数据');
 for(const t of Object.values(s.tasks)){if(!object(t)||(t.status&&!['todo','doing','blocked','done','waived'].includes(t.status))||(t.dueDate&&!validDate(t.dueDate)))throw Error('任务状态无效');}
 for(const [id,t]of Object.entries(s.customTasks)){if(!object(t)||t.id!==id||!id.startsWith('custom-')||typeof t.title!=='string'||!Number.isInteger(t.day)||t.day<1||t.day>30||!finite(t.minutes,5,600)||!Array.isArray(t.dependencies))throw Error('自定义任务无效');}
 for(const [id,x]of Object.entries(s.sessions))if(!object(x)||x.id!==id||!validDate(x.date)||!finite(x.minutes,0.1,1440)||typeof x.taskId!=='string')throw Error('学习记录无效');
 for(const [id,x]of Object.entries(s.expenses))if(!object(x)||x.id!==id||!validDate(x.date)||!finite(x.amount,0,10000000)||!finite(x.quantity,0,100000)||!finite(x.rate,0,1000000)||(x.stopAt&&!Number.isFinite(Date.parse(x.stopAt))))throw Error('费用记录无效');
 for(const [id,x]of Object.entries(s.experiments)){if(!object(x)||x.id!==id||typeof x.name!=='string'||!['planned','running','finished','failed'].includes(x.status))throw Error('实验记录无效');for(const k of ['correct','total','reward','tokens','turns','cost'])if(x[k]!==null&&x[k]!==''&&x[k]!==undefined&&!finite(x[k],k==='reward'?-1e9:0,1e12))throw Error('实验数值无效');if(x.correct!=null&&x.total!=null&&x.correct>x.total)throw Error('正确数不能超过样本数');}
 for(const x of Object.values(s.reviews))if(!object(x)||!validDate(x.due)||!finite(x.interval,0,365)||!finite(x.reps,0,100000))throw Error('复习记录无效');
 for(const key of ['journals','resources','milestones'])for(const x of Object.values(s[key]))if(!object(x))throw Error('记录格式无效：'+key);
 if(s.timer!==null){const t=s.timer;if(!object(t)||typeof t.id!=='string'||!['running','paused'].includes(t.status)||!['focus','break'].includes(t.mode)||!validDate(t.date)||!finite(t.durationMs,60000,10800000)||!finite(t.remainingMs,0,t.durationMs)||!finite(t.startedAt,0,1e16))throw Error('计时状态无效');}
 return s;
}
export function parseBackup(text){if(new TextEncoder().encode(text).length>8000000)throw Error('备份超过 8MB 限制');let raw;try{raw=JSON.parse(text);}catch{throw Error('不是有效 JSON 文件');}if(raw.format!=='llm-rl-mission-control'||raw.schemaVersion!==1||!raw.state)throw Error('不是本应用支持的备份');return validateState(raw.state);}
export function backupEnvelope(s){return {format:'llm-rl-mission-control',schemaVersion:1,planVersion:PLAN_VERSION,exportedAt:new Date().toISOString(),state:clone(s)};}
export function csv(rows){const cell=v=>{let t=String(v??'');if(typeof v!=='number'&&/^[\s]*[=+@\-]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"';};return '\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n');}
const icsEscape=s=>String(s).replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(';','\\;').replaceAll(',','\\,');
export function calendarICS(s){const dates=planDates(s),stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//RL Mission Control//Study Plan//ZH','CALSCALE:GREGORIAN'];for(const d of days){const date=dates[d.day];lines.push('BEGIN:VEVENT',`UID:rlmc-day${d.day}-${s.settings.startDate}@local`, 'DTSTAMP:'+stamp,'DTSTART;VALUE=DATE:'+date.replaceAll('-',''),'DTEND;VALUE=DATE:'+addDays(date,1).replaceAll('-',''),'SUMMARY:'+icsEscape(`D${d.day} ${d.title} · 10h`),'DESCRIPTION:'+icsEscape(d.sections+'\n产出：'+d.output+'\n当天单项改期请以工作台为准。'),'END:VEVENT');}lines.push('END:VCALENDAR');return lines.map(line=>{let out='',bytes=0;for(const ch of line){const n=new TextEncoder().encode(ch).length;if(bytes+n>73){out+='\r\n ';bytes=1;}out+=ch;bytes+=n;}return out;}).join('\r\n')+'\r\n';}
export function planMarkdown(s){const dates=planDates(s);return '# LLM RL · 30 天 / 300 小时\n\n课程版本 '+PLAN_VERSION+'。每日净学习 10h，普通算法保温已含在内。\n\n'+days.map(d=>`## Day ${d.day} · ${dates[d.day]} · ${d.title}\n\n前置：${d.day===1?'已有开发背景':'前一天实验验收；跨阶段还需阶段确认'}。\n\n`+tasks.filter(t=>t.day===d.day).map(t=>`### ${t.time} · ${t.kind} · ${t.minutes}min\n\n${t.description}\n\n验收：${t.acceptance}\n\n`).join('')+'资料（顺序）：\n'+d.resources.map(id=>{const r=resources.find(x=>x.id===id);return `- [${r.title}](${r.url})`;}).join('\n')+`\n\n回退：${d.fallback}\n\n`).join('');}
export function weeklySummary(s,fromDay=1){const selected=allTasks(s).filter(t=>t.day>=fromDay&&t.day<fromDay+7),dates=planDates(s),from=dates[fromDay],to=dates[Math.min(30,fromDay+6)];const actual=Object.values(s.sessions).filter(x=>x.date>=from&&x.date<=to).reduce((a,x)=>a+x.minutes,0);return `# D${fromDay}–D${Math.min(30,fromDay+6)} 周复盘\n\n已完成任务 ${selected.filter(t=>s.tasks[t.id]?.status==='done').length}/${selected.length}；掌握豁免 ${selected.filter(t=>s.tasks[t.id]?.status==='waived').length}。\n实际记录 ${(actual/60).toFixed(1)} h（${from} 至 ${to}）。\n\n## 已完成\n${selected.filter(t=>s.tasks[t.id]?.status==='done').map(t=>'- '+t.title).join('\n')||'尚无记录'}\n\n## 阻塞与未完成\n${selected.filter(t=>!isFinished(t,s)).map(t=>'- '+t.title+(s.tasks[t.id]?.blocker?'：'+s.tasks[t.id].blocker:'')).join('\n')||'本周全部处理'}\n\n## 下一周\n优先解决前置验收，再继续扩展实验。不要把计划学时当成实际学时。\n`;}
