/** Curriculum v1. Learning estimates are a plan, not claims of research results. */
export const PLAN_VERSION = '2026.09.26';
export const phases = [
  {id:0,name:'实验起点',en:'SETUP',start:1,end:1,gate:'能复现 forward、采样、设备与依赖清单。'},
  {id:1,name:'语言模型基础',en:'FOUNDATIONS',start:2,end:4,gate:'手写 attention、训练循环和 LoRA，并通过数值测试。'},
  {id:2,name:'监督与偏好对齐',en:'POST-TRAINING',start:5,end:7,gate:'解释 SFT mask、DPO 相对 logprob 与 RM 的评估局限。'},
  {id:3,name:'策略优化',en:'POLICY OPTIMIZATION',start:8,end:11,gate:'独立写出 PG / PPO / GRPO loss，验证 mask 与零方差。'},
  {id:4,name:'可验证推理',en:'REASONING RL',start:12,end:15,gate:'有 Base / SFT / GRPO 同口径评估，能解释失败轨迹。'},
  {id:5,name:'训练系统',en:'RL SYSTEMS',start:16,end:19,gate:'跑通小规模 verl，定位 rollout、reward、advantage 和 update。'},
  {id:6,name:'代码智能体',en:'AGENTIC RL',start:20,end:22,gate:'隔离环境可重置；动作 token mask 正确；终局 RL 有基线。'},
  {id:7,name:'验证与信用分配',en:'VERIFIER & CREDIT',start:23,end:25,gate:'能区分标量奖励塑形和逐步 advantage，审计隐藏测试泄漏。'},
  {id:8,name:'研究证据链',en:'CONTROLLED RESEARCH',start:26,end:29,gate:'主对照、消融、OOD、失败分析和复现实验都有可审计产物。'},
  {id:9,name:'作品与答辩',en:'PORTFOLIO',start:30,end:30,gate:'他人能照 README 复现，简历的每个数字都能定位原始记录。'}
];
const r=(id,title,type,url,scope,checked=false)=>({id,title,type,url,scope,checked});
export const resources = [
 r('torch','PyTorch · Learn the Basics','官方文档','https://pytorch.org/tutorials/beginner/basics/intro.html','Tensor、Autograd、Optimization Loop；只查漏补缺。'),
 r('hf','Transformers · Chat templates','官方文档','https://huggingface.co/docs/transformers/chat_templating','apply_chat_template、generation prompt、特殊 token。'),
 r('qwen','Qwen3-0.6B · Model card','模型','https://huggingface.co/Qwen/Qwen3-0.6B','模型加载、chat template、thinking 控制；作为可替换的教学基线。',true),
 r('cs336','Stanford CS336 · Spring 2026','课程','https://cs336.stanford.edu/','Lectures 1–3、10、12、15–16；Assignment 1 和 5 选做，不要求整课。',true),
 r('attention','Attention Is All You Need','论文','https://arxiv.org/abs/1706.03762','§3.2 Attention、§3.4 Embeddings、§3.5 Positional Encoding。',true),
 r('lora','LoRA','论文','https://arxiv.org/abs/2106.09685','§4 Method、§7 低秩分析；关注初始化与合并权重。',true),
 r('peft','PEFT · LoRA guide','官方文档','https://huggingface.co/docs/peft/developer_guides/lora','LoraConfig、target_modules、保存与加载 adapter。'),
 r('sft','TRL · SFTTrainer','官方文档','https://huggingface.co/docs/trl/sft_trainer','Dataset formats、loss masking、训练配置；版本变化时先跑 smoke test。',true),
 r('dpo','Direct Preference Optimization','论文','https://arxiv.org/abs/2305.18290','§3–4：KL 约束目标、最优策略与偏好损失。',true),
 r('dpot','TRL · DPOTrainer','官方文档','https://huggingface.co/docs/trl/dpo_trainer','偏好数据、reference、beta 与损失配置。',true),
 r('instruct','InstructGPT','论文','https://arxiv.org/abs/2203.02155','§3：SFT → RM → PPO 流程；数据与评估局限。'),
 r('rm','TRL · RewardTrainer','官方文档','https://huggingface.co/docs/trl/reward_trainer','chosen/rejected、pairwise loss 和评估。'),
 r('pg','Spinning Up · Policy gradient','课程','https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html','Deriving the Simplest Policy Gradient：log-derivative、reward-to-go、baseline。'),
 r('ppo','Proximal Policy Optimization','论文','https://arxiv.org/abs/1707.06347','§2–3、Algorithm 1：ratio、clipping 与 value loss。'),
 r('grpo','DeepSeekMath','论文','https://arxiv.org/abs/2402.03300','§4 Reinforcement Learning：GRPO 的采样、优势与目标。',true),
 r('grpot','TRL · GRPOTrainer','官方文档','https://huggingface.co/docs/trl/grpo_trainer','Quick Start、loss、metrics、Agent Training；agent 接口是实验性功能。',true),
 r('r1','DeepSeek-R1','论文','https://arxiv.org/abs/2501.12948','§2：R1-Zero、cold start、多阶段训练；不外推小模型结果。',true),
 r('gsm','GSM8K · Dataset card','数据集','https://huggingface.co/datasets/openai/gsm8k','训练/测试划分、答案格式、许可；测试集不能参与调参。'),
 r('verl','verl · Documentation','官方文档','https://verl.readthedocs.io/en/latest/','Getting Started、GRPO、配置和性能；记录 commit 与镜像标签。'),
 r('agent','verl · Agentic RL','官方文档','https://verl.readthedocs.io/en/latest/start/agentic_rl.html','异步 rollout、多轮工具、token 对齐；页面标注更新于 2025-07-15。',true),
 r('vllm','vLLM · Documentation','官方文档','https://docs.vllm.ai/en/latest/','Quickstart、serving、GPU memory；服务默认只绑定回环地址。'),
 r('dapo','DAPO','论文','https://arxiv.org/abs/2503.14476','方法中的 clip、dynamic sampling、token loss、长度处理。',true),
 r('docker','Docker · Runtime security','官方文档','https://docs.docker.com/engine/security/','容器隔离边界、权限、资源限制；不要把 Docker 当绝对安全沙箱。'),
 r('swe','SWE-bench · Documentation','评测','https://www.swebench.com/','仅后续外部评估入口；30 天不承诺完整榜单提交。'),
 r('happy','Happy-LLM · 中文补充','中文教材','https://datawhalechina.github.io/happy-llm/','Transformer 与微调部分；中文帮助理解，公式回到原论文核对。'),
 r('d2l','动手学深度学习 · 中文','中文教材','https://zh.d2l.ai/','自动微分、优化、注意力：按不懂的概念查阅，不从头刷。'),
 r('uv','uv · 项目与锁文件','官方文档','https://docs.astral.sh/uv/guides/projects/','init、add、lock、sync；本地与云端分开锁定。'),
 r('wandb','Weights & Biases · Experiments','官方文档','https://docs.wandb.ai/models/track','config、metrics、artifacts；公开前检查数据和敏感信息。')
];
// Each row describes a day, not a claim that all stretch experiments fit every GPU.
const rows = [
 ['环境与第一条证据链','设备、token 与最小 forward',['uv','torch','hf','qwen'],'uv projects；Torch Tensor/Autograd；Qwen Usage 与 chat template。','确认芯片 uname -m；隔离 learn / trl / verl 环境；理解 token、logits、概率与设备。','写 env_check.py 与 inspect_logits.py；加载 0.6B，forward 后手工取末 token 概率；设置固定种子。','同一输入复跑并记录环境；检验 tokenizer round-trip、输出 shape 和 CPU/MPS/CUDA 路径。','env_report.txt、requirements/lock、首个 commit、10 条固定评测 prompt。','网络或 MPS 出错时改 CPU + tiny 随机模型验证接口，不在安装上耗整天。','稳定 softmax（减 max）','215 · 数组中的第 K 个最大元素','kth-largest-element-in-an-array','为何 logits 不能直接当作概率？','logits 是未归一化分数；softmax 给出条件分布。数值稳定版本先减去最大值，避免指数溢出。'],
 ['Attention 从张量到代码','causal mask 与数值对齐',['attention','cs336','d2l'],'Attention §3.2；CS336 Architecture 中 attention 部分。','梳理 Q/K/V 形状、缩放、head 拆分与 causal mask；对比 padding mask。','实现 scaled_dot_product_attention 和 multihead wrapper；先不实现 RoPE/GQA 全家桶。','与 torch SDPA 的 eval 输出对齐；修改未来 token，验证过去输出不变；测试全 padding 边界。','attention.py、3 类测试、张量形状图。','先单头、长度 8、float32；误差定位后再增加 heads。','手写 attention / causal mask','347 · 前 K 个高频元素','top-k-frequent-elements','causal mask 与 padding mask 有什么不同？','causal mask 禁止访问未来位置；padding mask 屏蔽无效填充。两者作用不同，且必须与张量广播维度一致。'],
 ['语言模型训练循环','shift、loss、optimizer',['torch','cs336'],'CS336 A1 中 LM loss/optimizer；Torch Optimization Loop。','理解 next-token shift、交叉熵、梯度累积、AdamW、clip 和验证集。','不用 Trainer 写 tiny decoder LM 的 train/eval/save/resume；实现 masked cross entropy。','在小批数据上过拟合；比较正确 shift 与故意错位的 loss；核验累积梯度与大 batch（关闭 dropout）。','train_tiny.py、loss 图、可恢复 checkpoint。','用字符词表和两层网络，不在 tokenizer 工程上扩 scope。','logsumexp + masked cross entropy','3 · 无重复字符的最长子串','longest-substring-without-repeating-characters','梯度累积何时近似大 batch？','损失缩放、有效 token 权重和参数更新时间一致时；dropout、batch-dependent 层和数值精度仍可引入差异。'],
 ['LoRA 与训练资源账本','低秩更新与参数冻结',['lora','peft','qwen'],'LoRA §4；PEFT target_modules、保存/合并 adapter。','推导 W + (alpha/r)BA；理解冻结参数不等于消除激活和 rollout 显存。','实现 LoRALinear 并做 merge/unmerge；用 PEFT 在小模型注入；核验 trainable parameters。','比较 rank 4/8 的参数量与前向；确认冻结参数 grad 为空、adapter 有梯度。','lora.py、参数统计、阶段验收笔记。','正式 SFT 训练留到 D5；本日 GPU 非必须。','LoRALinear + 参数量估算','34 · 排序数组查找边界','find-first-and-last-position-of-element-in-sorted-array','LoRA 为什么不等于训练显存按参数比例下降？','优化器状态减少，但基础权重、激活、KV cache 和生成过程仍消耗显存；实际峰值需测量。'],
 ['SFT 与数据边界','模板、mask、固定评测',['sft','hf','peft'],'SFT Dataset formats / loss；Chat templates。','设计 500–1000 条小型训练样本；独立 dev/test；先审计重复、格式和许可。','实现数据检查器；SFT+LoRA；打印一条样本逐 token labels，确认 prompt/pad 不参与目标 loss。','先 10 steps smoke test，再短训；Base 与 SFT 用同一套 30–50 prompts 评估。','sft config、adapter、数据 hash、Base/SFT 表。','显存不足依次降长度/batch、用 checkpointing；不要马上换更大卡。','label shift / assistant mask','146 · LRU 缓存','lru-cache','assistant-only loss 最容易错在哪里？','模板是否提供 assistant mask、特殊 token 的归属、截断和多轮边界都要核查；仅设置一个参数不足以证明 mask 正确。'],
 ['DPO 的相对偏好目标','reference 与 beta',['dpo','dpot'],'DPO §3–4；DPOTrainer 数据与参数。','先补 Bradley–Terry 的 sigmoid 偏好概率，再推导 chosen/rejected 的相对 logprob；RM 训练不是 DPO 前置。','手写 dpo_loss 并对齐符号；构造 200–500 对偏好数据；小步 DPO，保存 reference 标识。','交换 chosen/rejected 检验方向；记录 margin 与 held-out preference accuracy，防止把长度偏好当质量。','dpo_loss.py、toy run、偏好审计表。','卡住时完成 tensor 级 loss 和离线评估，不做整套 RLHF。','DPO loss / logsigmoid','208 · 实现 Trie','implement-trie-prefix-tree','DPO 是否证明不再需要 reward？','它通过重参数化将偏好学习转成直接策略目标，不是说偏好数据或评价标准不重要，也不是所有 RL 都能被替代。'],
 ['Reward Model 与验证器','偏好预测不是客观正确性',['instruct','rm'],'InstructGPT §3；RewardTrainer chosen/rejected。','比较 preference RM、规则 verifier 和最终任务指标；理解 reward hacking 的代理目标。','写 pairwise reward head 与 loss；小数据训练/验证；对长度、乱码、重复构造对抗样本。','报告 held-out pairwise accuracy、长度相关性、至少 5 个误判；复核 SFT/DPO 链路。','rm_toy.py、failure_cases.jsonl、后训练流程图。','只训 tiny reward head；不为完成清单去训练大 RM。','Bradley–Terry pairwise loss','56 · 合并区间','merge-intervals','RM 分数上升为什么不能直接证明任务能力变强？','RM 是有误差的代理目标；策略可能利用长度、格式或分布外漏洞。必须用独立任务指标和保留集验证。'],
 ['Policy Gradient 基础','状态、动作、回报、baseline',['pg','d2l'],'Policy gradient 推导中的 log-derivative、reward-to-go 与 baseline。','从有限 MDP 写出 trajectory likelihood 和 J(theta)；区分 V、Q、A。','手写 bandit/CartPole REINFORCE；保存 sampled actions、logprobs 与 returns。','做 3 个随机种子；对比有/无 baseline 的梯度方差，不只看一次成功曲线。','reinforce.py、seed 表、策略梯度推导。','先做 2-arm bandit，省去环境依赖和长时训练。','reward-to-go / REINFORCE loss','102 · 二叉树层序遍历','binary-tree-level-order-traversal','baseline 为什么可以降低方差而不改变期望梯度？','与当前动作无关的 baseline 在策略分布下乘 score function 的期望为零；实现时不要让 baseline 的梯度混入策略项。'],
 ['PPO 的可控更新','ratio、clip 与 advantage',['ppo','pg'],'PPO §2–3、Algorithm 1；先理解 clipped surrogate。','推导新旧策略概率比；区分 old policy 和 reference policy；学习 GAE 的递推。','实现 ppo_loss、GAE、entropy；用 tiny policy 跑短实验。','用正/负 advantage 测 clipping 分支；detach old logprob；检查 ratio=1 时的行为。','ppo_loss.py、gae.py、单元测试。','训练不收敛先看 tensor 单测，不能靠调学习率掩盖符号错误。','PPO clip loss + GAE','207 · 课程表','course-schedule','old policy 和 reference model 是一回事吗？','old policy 是采样时的行为策略，用于重要性比率；reference 通常是固定约束基准，用于 KL。二者职责不同。'],
 ['LLM 如何成为策略','token logprob 与 KL',['grpo','grpot','cs336'],'GRPO 文档中的 objective / metrics；CS336 RLVR。','映射 state=上下文、action=token、trajectory=completion；区分 KL 估计与完整分布 KL。','写 gather_token_logprobs、masked sequence sum、KL estimator；不重 tokenize 已有 rollout。','人工构造两 token 词表核验概率；检查 padding、EOS、截断、prompt 和 observation mask。','logprobs.py、mask_tests.py、手算对照。','先在人工 logits 上全部通过，再接真实模型。','gather logprob / KL','743 · 网络延迟时间','network-delay-time','为什么不能对工具 observation token 计算策略 loss？','它们由环境产生而非策略采样；把它们当 action 会改变目标。必须保持原始 token 对齐并用 action mask。'],
 ['GRPO：从公式到最小实现','group advantage 与零方差',['grpo','grpot','r1'],'DeepSeekMath §4；R1 §2；GRPO loss 与 batch 配置。','推导组内 reward 标准化；解释无独立 critic 的取舍与全对/全错组的信号问题。','实现 group_advantage 与 masked GRPO objective；显式指定 loss_type，不假定默认等于原论文。','测试组大小、零 std、全 masked、ratio clip；核对 global generation batch 能被 G 整除。','grpo_core.py、公式到源码映射、阶段验收。','先只实现原始教学目标；新变体留到 D19。','GRPO advantage + zero-variance','684 · 冗余连接','redundant-connection','全组 reward 相同会发生什么？','组内标准化优势接近零，当前组不能区分更好的回答；应记录零方差比例，调整任务难度或采样，而不是伪造奖励差异。'],
 ['第一个 Reasoning RL','先评测，再短训',['gsm','grpot','qwen'],'GSM8K card；GRPO Quick Start；Qwen generation 配置。','从训练集划 dev，test 冻结；精确答案解析器拒绝模糊提取；固定 seed、token budget 与模型模式。','TRL + LoRA；先 8 prompts/10 updates smoke test，再 100–300 updates 上限；从已验证 checkpoint 起跑。','比较 Base/SFT/GRPO；记录 reward、std、长度、entropy、KL（开启时）和 GPU 峰值。','first_grpo config、run ID、评测 JSONL。','若 0.6B 几乎全错先降低题目难度；优先修 reward，不盲目升级模型。','鲁棒答案 parser + 单测','398 · 随机数索引','random-pick-index','为什么 test 不能用来挑超参数？','反复依据 test 选择设置会把评估集变成隐性训练信号；dev 用于选择，test 用于冻结后的最终报告。'],
 ['采样效率与训练诊断','只改一个变量',['grpot','grpo'],'GRPO metrics、num_generations、generation lengths。','制定 G=2/4 的对照；固定总生成 token 或明确算力差异；G=8 仅预算允许。','写实验配置生成器；添加奖励分布、零方差组比率、异常长度和 OOM 捕获。','先做两条短 run，不进行全网格搜索；用相同 dev 比较质量/成本。','sampling_ablation.json、曲线、成本说明。','预算告警后保留两组；若差异噪声大如实报告。','top-k / top-p sampling','560 · 和为 K 的子数组','subarray-sum-equals-k','比较 G 时为什么要报告 token 成本？','增加组大小改变采样量和训练信号质量；只比较更新步数会混淆算法收益与额外计算收益。'],
 ['Reward Hacking 实验','有意构造一个坏目标',['r1','grpot','rm'],'R1 reward design；GRPO reward functions。','明确代理奖励与最终正确率；设计长度或格式奖励的反例，不将它用于主模型结论。','离线重打分或短 run 展示重复/关键词 exploit；修复 parser、设置无效输出处理。','列出至少 10 条失败样本；分别画 proxy reward 与独立 accuracy。','reward_audit.md、bad_cases.jsonl、修复测试。','不必烧 GPU 让模型真的崩塌；离线构造反例也能验证漏洞。','reward normalization / clipping','239 · 滑动窗口最大值','sliding-window-maximum','把 reward clip 之后就不会被利用了吗？','clip 限制量级，不修复评价目标本身的漏洞。仍需独立 verifier、隐藏评估与失败审计。'],
 ['评测与第一轮封板','pass@k、置信区间、可复现',['cs336','gsm','grpot'],'CS336 Evaluation；GRPO eval；保留集协议。','区分 greedy accuracy、sampled pass@1、pass@k 与 best-of-N；选择只报告真正测过的指标。','实现逐样本 evaluator、bootstrap 区间与配置 hash；导出 Base/SFT/GRPO 表。','固定解码协议和 test；检查题目重复、parser 失败分母；30–100 个小 test 明确限制。','Reasoning Lab v0.1、eval_manifest.json、阶段总结。','没有提升也保留正确基线；不要改 test 换好看的数字。','pass@k 估计器 / bootstrap','322 · 零钱兑换','coin-change','小测试集上提升 2 个样本代表什么？','这是有限样本下的观察，不足以直接宣称稳定提升；报告样本数、区间、种子与失败案例。'],
 ['verl 系统地图','actor / rollout / reference',['verl','agent'],'verl Getting Started、GRPO example、架构说明。','按实际使用的 release/commit 阅读；理解 Ray、FSDP、rollout server 的职责。','创建独立云环境；先检查 NVIDIA 驱动、镜像、磁盘和权限；跑官方最小配置。','绘制 batch 在各模块的 shape 与流向；记录依赖锁和镜像摘要。','verl_environment.md、架构图、smoke log。','超过 4 小时依赖问题则回到 TRL 完成主线；记录问题而不是无限装包。','batch reshape / group ordering','39 · 组合总和','combination-sum','RL 系统为什么不能只看 trainer？','生成、环境、奖励、参考模型和更新组成闭环；吞吐、权重版本、token 对齐与数据顺序都可能影响正确性。'],
 ['verl 小模型 GRPO','配置、日志、可恢复性',['verl','grpo'],'verl GRPO 和 config；只读所用后端相关部分。','映射 actor / ref / rollout 配置；理解 rollout 权重同步与训练 checkpoint。','移植 D12 的同一小任务；保持 reward / data hash 一致；跑最短可用训练。','比较两框架差异的可能来源，不强求 bitwise 一致；检查恢复训练。','verl run、config diff、恢复实验。','单卡不够就保留已跑通的 TRL；系统阅读仍按计划完成。','masked mean / token-weighted loss','98 · 验证二叉搜索树','validate-binary-search-tree','checkpoint 相同为什么仍可能结果不同？','解码、随机数、模板、tokenizer、精度和并行归约不同都可能影响结果，必须记录环境与评测协议。'],
 ['推理和显存工程','KV cache、batching、并行',['vllm','cs336','verl'],'CS336 Inference / Parallelism；vLLM Quickstart / serving。','区分 FSDP、DP、TP；估算权重、优化器、激活和 KV cache；不做完整分布式实现。','起小模型服务于 127.0.0.1；经 SSH tunnel 访问；测两种并发与长度。','记录 tokens/s、延迟、显存；解释 rollout 等待工具时的 GPU idle。','serving_bench.json、显存账本、SSH 使用说明。','vLLM 不兼容 Mac 时只用 Linux；不把 MPS 当 CUDA。','KV cache 大小估算','23 · 合并 K 个升序链表','merge-k-sorted-lists','增大并发为何可能让延迟变差？','吞吐与单请求延迟存在取舍；更大 batch、KV 占用和排队会影响尾延迟，应同时报告二者。'],
 ['现代 GRPO 变体','理解设计维度而非追新名词',['dapo','verl','grpot'],'DAPO 方法；对照所用框架的 loss_type / sampling。','比较非对称 clip、动态采样、token-level aggregation、超长截断；区分论文和实现默认。','选一个变体做 tensor loss 对照或已有 checkpoint 短实验，保持其余设置一致。','写 GRPO/DAPO 差异矩阵；解释每项试图修复的失败模式。','loss_comparison.md、一个受控对照。','不把 DPPO/GSPO 等全部加入必做；先确保 GRPO 主线可解释。','token vs sequence aggregation','528 · 按权重随机选择','random-pick-with-weight','token-level 聚合和逐步信用分配是同一件事吗？','不是。前者决定损失如何加权聚合，后者涉及给不同动作分配何种学习信号；名字类似但目标不同。'],
 ['最小 Code Agent','有限工具与状态机',['agent','grpot','docker'],'Agent loop、tool schema、GRPO Agent Training；先读版本说明。','选择小型纯 Python 单函数修复；限定 read/edit/test 三工具、最多 4 turns；不用真实大仓库。','写 CodingEnv.reset/step 与 trajectory schema；任务按模板族划 train/dev/test；生成 60–100 条可审计任务。','每个任务先验证错误版 fail、正确版 pass；拒绝可写测试；保存状态和 tool errors。','environment.py、task_manifest、10 条 rollout。','先只做 10 个任务，验证端到端；不扩展到 SWE-bench 全量。','有类型的 tool dispatcher','621 · 任务调度器','task-scheduler','为什么要在训练前验证每个任务可解？','不可解或测试错误的任务会污染 reward；模型失败与环境错误必须分离，否则实验归因无效。'],
 ['隔离执行与数据集协议','隐藏测试和工具安全',['docker','agent'],'Docker security；Agent loop token alignment。','区分 visible tests、训练 reward tests 与最终 sealed test；最终测试不进入 rollout。','沙箱无网络、非 root、资源/时长限制、只读测试、每 episode 重建；记录 action mask 与工具输出。','测试 timeout、语法错、重复 edit、污染测试和跨 episode 状态泄漏；容器不能访问宿主凭据。','sandbox_tests、split_hashes、威胁模型。','容器权限不足用独立 CPU VM；绝不在个人 Mac 宿主直接执行模型任意代码。','trajectory parser / action mask','49 · 字母异位词分组','group-anagrams','为什么训练 reward tests 不能被称为真正隐藏评估？','只要其反馈进入训练，模型就能间接适应该测试；最终 sealed test 必须完全隔离。'],
 ['Agentic RL 终局基线','先跑 outcome-only',['agent','grpot'],'所用版本的 environment_factory/reset/get_reward；不要跨版本抄参数。','审计环境 API 生命周期；用 D20–21 的任务验证 model 对工具格式的能力。','先 Base/SFT agent，再 outcome-only GRPO；reward 为训练侧任务成功，记录动作 token masks。','同一 harness/dev 集评测成功率、步数、token、工具错误；确认 group 有可学习差异。','Base/SFT/Outcome-GRPO 表、可复现轨迹。','在线 RL 跑不稳则 verifier + rejection sampling/SFT；报告明确写离线方案。','episode reward / truncation handling','703 · 数据流中的第 K 大元素','kth-largest-element-in-a-stream','工具输出重新分词为什么可能损坏训练？','它可能改变 token 边界和 action/logprob 对齐。生成时的 token IDs 与概率需要完整保留，环境 token 另做 mask。'],
 ['Verifier 工程','成功、进展与回归分开',['agent','rm'],'回看 reward 模块与环境协议；本日以自主实现和审计为主。','定义 terminal success、测试进展、regression、tool validity；运行成功不代表语义正确。','实现结构化 TestResult 解析；设计正常/恶意 trajectory 的 verifier 单测。','盲审 20 条轨迹；审计测试篡改、重复运行刷分、无意义格式通过。','verifiers.py、误判矩阵、20 条审计样本。','先做可靠的 outcome verifier；没有可靠 signal 就不加复杂 reward。','test delta / regression detector','435 · 无重叠区间','non-overlapping-intervals','工具执行成功等于任务变好了吗？','不等于。cat/grep 成功只说明执行有效，未必促进修复；把它当正奖励可能诱导无意义重复调用。'],
 ['信用分配与研究假设','不要把 shaping 写成新算法',['grpo','dapo','agent'],'复核 GRPO advantage；梳理自己采集的 step reward 与 loss mask。','明确三层：标量 shaping、按步回报、逐步 advantage；势函数 shaping 的不变性需要特定条件，不能随意 clip 后宣称成立。','解析每次 edit/test 的状态差异；离线比较 terminal-only 与 test-delta 的信号位置；先写假设与混杂因素。','检查只改变标量 R 时仍是 sequence reward；要称逐步 credit 必须说明每步 A_t 如何进入 loss。','hypotheses.md、step_credit_audit.json、方法定义。','逐步目标实现来不及，主项目改名为 Verifier-Guided Reward Study，保留研究诚实性。','reward-to-go / per-step advantage','300 · 最长递增子序列','longest-increasing-subsequence','R=aR1+bR2 是否已经实现 step-level credit assignment？','没有。它只定义了标量奖励；若所有动作仍用同一优势，本质是奖励塑形。逐步 credit 需明确动作级回报/优势及其估计方式。'],
 ['固定主项目协议','预注册与小试验',['grpot','agent'],'自己的协议与 verifier tests；只回查相关 API。','冻结模型、数据、harness、token budget、终止规则；命名 VGCA-RL 为研究工作名，不宣称新算法。','定义 E0 Base、E1 SFT、E2 outcome-GRPO、E3 outcome+test-delta shaping；可选 E4 逐步 credit。','每组 10–20 任务 pilot；检查 reward hacking、全零组、成本和吞吐；满足条件才扩实验。','protocol_v1.md、预注册实验矩阵、预算上限。','删去 E4 与 scale test 也保留完整主对照；不以更多方法代替正确实验。','固定 seed / run manifest','139 · 单词拆分','word-break','为什么实验协议应先于主结果冻结？','减少看到结果后不断更换指标、数据或对照的选择偏差；任何事后探索都应另行标注。'],
 ['主对照实验','同模型同数据同预算',['grpot','wandb'],'协议 v1；W&B config/metrics/artifacts。','复核比较单位是样本、更新步还是生成 token；定义提前停止条件。','按预算运行 E2/E3；尽量 2–3 seeds，小预算优先主对照，保存原始输出而非只有均值。','记录准确分子/分母、区间、平均 turns、token 和实际花费；不能将训练 reward 当结论。','main_results.jsonl、configs、run links。','剩余预算不足时缩训练步数、固定单模型；说明统计局限。','bootstrap paired delta','5 · 最长回文子串','longest-palindromic-substring','如何避免让实验组靠更多 rollout 获胜？','固定或报告生成 token/样本预算；同时给出质量与成本，以区分计算量增加和方法本身的收益。'],
 ['消融与复跑','一次移除一个因素',['dapo','grpo'],'自己的方法定义与对照协议。','选 2 个必要消融：去 test-delta、去 regression guard；不做无边界超参网格。','从一致 checkpoint 起跑；验证 reward scale 与学习率混杂；重跑主对照关键 seed。','输出 ablation 表和失败轨迹；如 E3 更差，保留负结果并解释可证据支持的机制。','ablation.json、seed_manifest、局限说明。','先完成 1 个高质量消融与复跑，不为凑表造数字。','confidence interval / seed aggregation','295 · 数据流的中位数','find-median-from-data-stream','消融能直接证明因果吗？','只有在控制其他条件并考虑随机性等限制时才提供较强证据；多个同时变化的设置不能被归因给一个组件。'],
 ['OOD 与失败剖析','模板族隔离与难度迁移',['swe','agent'],'本项目 split protocol；SWE-bench 仅作后续外部验证参考。','冻结 20–40 个未见模板族/更长任务；同模板换数字不算强 OOD。','评测未见 bug family、更长 horizon 和工具故障；标注 reasoning/tool/verifier/regression failure。','抽取至少 10 个失败轨迹逐步解释；外部 benchmark 最多少量 smoke test，不能冒充完整得分。','ood_results、failure_taxonomy.md、代表性案例。','放弃外部大仓库评测也要保住真正独立的 OOD split。','failure taxonomy / metrics aggregator','76 · 最小覆盖子串','minimum-window-substring','仅把同一题目里的数字换掉算强 OOD 吗？','通常只能说明有限扰动鲁棒性。未见模板族、任务机制或仓库隔离才是更有意义的分布变化，并需明确描述。'],
 ['技术报告与复现','别人能否独立验证',['wandb','cs336'],'自己的原始产物；课程 honor code：区分自主实现和借用代码。','写问题、方法、实验、结果、局限；明确未同行评审，负结果和失败实验也记录。','从干净环境复现 smoke test；补许可证、数据来源、成本、版本锁、模型卡和 3–5 分钟 demo。','README 的每个数字链接到 run/原始表；无 API key、私有数据或隐藏测试泄漏。','technical_report.md、README、model card、reproduce.sh。','不花整天美化封面；优先修不能运行的复现命令。','最小可复现故障定位','200 · 岛屿数量','number-of-islands','如何让没有论文的项目具有可信度？','公开可复现配置、对照和原始记录；明确局限、不夸大新颖性。可信度来自可核查过程，不来自项目名字。'],
 ['发布、答辩与后续路线','以证据而非词汇求职',['cs336','grpo','agent'],'只复习薄弱项；用项目代码而非背诵模板准备。','准备 10 分钟讲解：问题1/方法2/实现2/实验2/失败2/下一步1；列出下一阶段60–90天计划。','打 release/tag；完整作品索引；写 3 条带真实数据的简历 bullet；做一次不看笔记演示。','模拟回答 loss、mask、reward hacking、训练成本和失败归因；未完成项如实列入 backlog。','release、报告、demo、简历、复盘与续学清单。','30 天是有边界的作品冲刺，不是研究能力或录用保证；优先交付诚实可复现版本。','抽签手写 PPO/GRPO + 讲代码','错题重做 · 任选薄弱题','two-sum','什么时候可以在简历中写提升了 X%？','有清楚基线、同口径测试、原始分子分母和统计限制时；区分百分点与相对百分比，不把 dev 最佳 run 当普遍结果。']
];
export const days = rows.map((x,i)=>({day:i+1,phase:phases.find(p=>i+1>=p.start&&i+1<=p.end).id,title:x[0],focus:x[1],resources:x[2],sections:x[3],theory:x[4],build:x[5],experiment:x[6],output:x[7],fallback:x[8],ml:x[9],drill:x[10],drillUrl:'https://leetcode.cn/problems/'+x[11]+'/',question:x[12],answer:x[13]}));
export const slots = [
 {key:'theory',name:'概念与推导',kind:'理论',minutes:120,time:'09:00–11:00'},
 {key:'source',name:'论文与源码',kind:'阅读',minutes:90,time:'11:15–12:45'},
 {key:'build',name:'动手实现',kind:'代码',minutes:210,time:'14:00–17:30'},
 {key:'verify',name:'实验与验收',kind:'实验',minutes:120,time:'18:30–20:30'},
 {key:'recall',name:'ML Coding / 算法保温',kind:'复习',minutes:30,time:'20:40–21:10'},
 {key:'ship',name:'记录与交付',kind:'交付',minutes:30,time:'21:10–21:40'}
];
export const tasks = days.flatMap(d=>slots.map((s,i)=>({
 id:`d${String(d.day).padStart(2,'0')}-${s.key}`,day:d.day,phase:d.phase,title:s.name+' · '+(i===4?d.ml:d.title),kind:s.kind,minutes:s.minutes,time:s.time,
 description:[d.theory,d.sections,d.build,d.experiment,`20 分钟手写 ${d.ml}；10 分钟恢复 ${d.drill}。已掌握的普通题用边界与复杂度口述，不额外加时。`,`整理 ${d.output}；记录今天的失败、假设、实际成本与明天的最小步骤。`][i],
 acceptance:[`能脱稿解释：${d.question}`,`写出一页公式/源码映射，注明版本；不把二手笔记代替原文。`,`代码可运行，有正例、反例、边界测试；预期输出与实现对应。`,d.experiment,`独立写出核心实现并说明复杂度/数值边界；暴露薄弱项进入复习队列。`,`产出可定位：${d.output}；提交真实证据链接，未完成项进入 backlog。`][i],
 resources:d.resources,fallback:d.fallback,
 dependencies:i===0?(d.day===1?[]:[`d${String(d.day-1).padStart(2,'0')}-verify`]):i===1?[`d${String(d.day).padStart(2,'0')}-theory`]:i===2?[`d${String(d.day).padStart(2,'0')}-source`]:i===3?[`d${String(d.day).padStart(2,'0')}-build`]:i===4?[`d${String(d.day).padStart(2,'0')}-theory`]:[`d${String(d.day).padStart(2,'0')}-verify`]
})));
export const milestones = [
 {id:'m1',day:4,title:'可解释的训练基础',detail:'attention / train loop / LoRA + 单元测试',evidence:'代码与测试链接'},
 {id:'m2',day:7,title:'后训练工具箱',detail:'SFT / DPO / RM 小实验与误判分析',evidence:'配置和对照表'},
 {id:'m3',day:15,title:'Reasoning Lab v0.1',detail:'Base / SFT / GRPO + 冻结评测协议',evidence:'评测 JSONL / run'},
 {id:'m4',day:19,title:'训练系统可复现',detail:'verl smoke test、数据流图、服务性能',evidence:'环境锁与实验记录'},
 {id:'m5',day:22,title:'Code Agent 基线',detail:'隔离环境、固定 split、outcome-only baseline',evidence:'轨迹与沙箱测试'},
 {id:'m6',day:25,title:'研究协议冻结',detail:'VGCA-RL 工作名；明确 shaping vs credit',evidence:'方法定义与预注册协议'},
 {id:'m7',day:28,title:'可核查的对照实验',detail:'主对照、消融、OOD 和负结果',evidence:'原始结果、区间与成本'},
 {id:'m8',day:30,title:'可交付作品集',detail:'README / 报告 / adapter / demo / 简历',evidence:'release 与作品索引'}
];
export const guideSections = [
 {title:'先读：范围与来源',body:'本课程基于用户的 ECA-RL / Post-Training 方向和后续确认的 30 天路线重构，不再补普通开发基础。每天净学习 10h，休息不计入。课程排期、验收和缩范围方案是本项目的学习设计，不是引用论文的实验结果。保留 Code RL、Verifier、Credit Assignment 主线；将大仓库、多模型扩展移到后续 60–90 天。标量 reward 加权只称奖励塑形，真正逐步 credit 必须修改并验证动作级学习信号。'},
 {title:'Mac · 第一天安装顺序',body:'先运行 uname -m / sw_vers / df -h，确认是 Apple Silicon 还是 Intel。安装 Xcode Command Line Tools、Homebrew、Git、uv、VS Code。Python 教学环境选 3.11；用 uv init --python 3.11，再 uv add torch numpy pytest matplotlib transformers。保存 uv.lock。学习环境与云端 trl / verl 环境分开，不一次安装所有框架。Docker Desktop 在 D20 前按官方文档安装并核验使用许可。MPS 不可用时以 CPU 跑张量练习；正式 RL 放到 Linux NVIDIA。'},
 {title:'模型与磁盘规则',body:'本地只留教学小模型与代码，HF_HOME 指到固定缓存目录；建议模型缓存≤60GB、数据≤25GB、Docker≤25GB、保留至少80GB空闲，先按真实剩余空间调整。0.6B 用来验证闭环，不代表长期最佳模型。Qwen3.5 等更新模型只在主线稳定后试验，不能为了新名字烧掉调试时间。删除缓存前看清路径；Adapter 优先于重复保存完整权重。'},
 {title:'云 GPU · 先检查再付费',body:'登录后运行 uname -m、nvidia-smi、df -h、free -h；确认所租 GPU 与镜像 CUDA/PyTorch 兼容。24GB 卡先小 LoRA / 短 rollout smoke test，能否容纳取决于长度、G、batch 与后端，不做装得下保证。需要更大显存时再选择48GB/80GB。vLLM/verl 优先官方配套镜像或锁定依赖，服务只绑定127.0.0.1，通过SSH tunnel访问。云实例可能不支持嵌套Docker。'},
 {title:'预算 · 总额不超过 5000 元',body:'预算为人民币规划值，不是实时 GPU 报价。2000 档：基础200、推理RL400、Agent主线500、主对照500、存储100、预备300。3500 档：300/600/900/900/200/600。5000 档：400/900/1300/1400/300/700。以控制台实际单价记账；实验页成本只是估计，账本才进入总支出，避免重复。先跑10步、再确认梯度与reward、最后放大。设置关机提醒，但本网页不会替你关闭 GPU。'},
 {title:'实验底线 · 测试不等于结论',body:'固定模型、split hash、harness、decode、seed 与 token budget；报告正确数/总数，不把 Reward 当 Success。训练 reward tests 不是最终 hidden evaluation。对比先做 Base、SFT、outcome-GRPO 和 shaping-GRPO；逐步 credit、2B/4B规模实验和 SWE-bench 仅选做。结果为负也可以是合格作品，禁止预填提升数字。'},
 {title:'卡住时 · 四小时止损',body:'框架兼容问题超过4小时：回到最后可运行的TRL环境；显存不足：先降低长度和batch；奖励全零：先验证题目可解与parser；D22在线Agent RL不稳定：转 verifier + rejection sampling / SFT，并明确标注离线方案。验收没通过可顺延；不要把300小时变成“每天再加两小时”。'},
 {title:'持久化与隐私',body:'进度在当前浏览器/当前站点本地保存，不上传 GitHub，也没有账号或跨设备实时同步。IndexedDB 主存储、localStorage 镜像/降级、自动快照与 JSON 备份各有用途；它们不能抵御用户清空网站数据。每周导出 JSON 到本地/iCloud；换域名、端口、浏览器或设备后导入。私密/无痕窗口不适合长期使用。申请持久存储不保证浏览器批准。公开仓库只包含应用与课程；不要在笔记里存 API key。'},
 {title:'怎样使用这个工作台',body:'总览看今天与逾期；计划页可改开始日/休息日，任务详情可补记时间、记录阻塞与证据；前置严格模式默认开启，但已掌握项可填理由豁免。任务完成获得的是计划学时，不会伪造实际学习时长；实际时长来自计时或手动记录。复习卡按自评安排下次复习。所有外链只在点击时打开，应用本身不调用模型或付费 API。'},
 {title:'30 天之后',body:'D31–60：扩大任务族、增加2–3个种子，补足统计功效；研究真正逐步advantage与有效对照。D61–90：再加入更大模型、外部仓库环境和有边界的SWE评测。实习投递使用公开产物证明实现与实验能力；这份计划不承诺录用或算法创新。'}
];
