import {initialState,validateState,clone,uid} from './core.js';
/** Read/modify/write transactions serialize mutations across tabs. No network storage. */
export class LocalStore{
 constructor(){const scope=new URL('../',import.meta.url).pathname;this.name='rlmc-v1:'+scope;this.key=this.name+':mirror';this.db=null;this.mode='memory';this.state=initialState();this.queue=Promise.resolve();this.source=uid();this.onChange=()=>{};this.warning='';}
 async open(){
  try{this.db=await new Promise((resolve,reject)=>{const req=indexedDB.open(this.name,1);let finished=false;const timeout=setTimeout(()=>{if(!finished){finished=true;reject(Error('数据库被其他窗口阻塞'));}},4500);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('data'))db.createObjectStore('data');if(!db.objectStoreNames.contains('snapshots'))db.createObjectStore('snapshots');};req.onsuccess=()=>{clearTimeout(timeout);if(finished){req.result.close();return;}finished=true;resolve(req.result);};req.onerror=()=>{clearTimeout(timeout);finished=true;reject(req.error);};req.onblocked=()=>{this.warning='旧窗口阻塞了数据库；请关闭旧页面后刷新。';};});this.mode='indexeddb';this.db.onversionchange=()=>{this.db.close();this.warning='数据库版本已变化，请先导出再刷新。';};}catch{try{localStorage.setItem(this.name+':probe','1');localStorage.removeItem(this.name+':probe');this.mode='localstorage';this.warning='IndexedDB 不可用，已降级到 localStorage。建议关闭其他同站点窗口并经常备份。';}catch{this.mode='memory';this.warning='浏览器禁止了持久化。当前仅在内存中保存，请立即导出 JSON，关闭会丢失。';}}
  const raw=this.db?await this.readDB():this.readMirror();if(raw)this.state=validateState(raw);else{const mirror=this.readMirror();if(mirror)this.state=validateState(mirror);if(this.db)await this.writeInitial();}
  if('BroadcastChannel'in globalThis){this.channel=new BroadcastChannel(this.name);this.channel.onmessage=e=>{if(e.data?.source!==this.source)this.reload().catch(()=>{this.warning='另一窗口数据无法加载，请先备份。';this.onChange({external:true});});};}
  globalThis.addEventListener('storage',e=>{if(e.key===this.key)this.reload().catch(()=>{});});return this.state;
 }
 readMirror(){try{const text=localStorage.getItem(this.key);return text?JSON.parse(text):null;}catch(e){if(e instanceof SyntaxError)throw Error('本地镜像损坏。请在恢复页导出原始数据，不能自动重置。');return null;}}
 readDB(){return new Promise((resolve,reject)=>{const tx=this.db.transaction('data','readonly'),req=tx.objectStore('data').get('root');req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>reject(req.error);});}
 writeInitial(){return new Promise((resolve,reject)=>{const tx=this.db.transaction('data','readwrite');tx.objectStore('data').put(this.state,'root');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
 async reload(){const raw=this.db?await this.readDB():this.readMirror();if(raw&&raw.revision>this.state.revision){this.state=validateState(raw);this.onChange({external:true});}}
 mutate(fn,{snapshot=false,replacement=null}={}){
  // Recovery creates a fresh validated object rather than merging corrupted/unknown keys.
  if(replacement)validateState(replacement);
  const prepare=old=>{const value=replacement?clone(replacement):clone(old);if(!replacement)fn(value);const revision=Number.isSafeInteger(old?.revision)&&old.revision>=0?old.revision:0;value.revision=revision+1;value.updatedAt=Date.now();validateState(value);return value;};
  const op=async()=>{let next;if(this.db){next=await new Promise((resolve,reject)=>{const tx=this.db.transaction(['data','snapshots'],'readwrite'),store=tx.objectStore('data'),req=store.get('root');let value;req.onsuccess=()=>{try{const old=req.result??this.state;value=prepare(old);if(snapshot||value.revision%20===0){const snaps=tx.objectStore('snapshots');snaps.put({at:Date.now(),revision:Number.isSafeInteger(old?.revision)?old.revision:0,state:old},`${Date.now()}-${uid()}`);const keys=snaps.getAllKeys();keys.onsuccess=()=>{keys.result.slice(0,Math.max(0,keys.result.length-7)).forEach(k=>snaps.delete(k));};}store.put(value,'root');}catch(e){tx.abort();reject(e);}};tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error||Error('保存失败'));tx.onabort=()=>reject(tx.error||Error('保存已取消'));});}else{
    const change=()=>{let old=this.state;if(this.mode==='localstorage'){try{old=this.readMirror()??this.state;}catch(e){if(!replacement)throw e;old={rawMirror:localStorage.getItem(this.key),revision:0};}}const value=prepare(old);if(this.mode==='localstorage'){if(snapshot||value.revision%20===0){try{const snaps=JSON.parse(localStorage.getItem(this.name+':snapshots')||'[]');snaps.push({key:uid(),at:Date.now(),revision:Number.isSafeInteger(old?.revision)?old.revision:0,state:old});localStorage.setItem(this.name+':snapshots',JSON.stringify(snaps.slice(-5)));}catch{this.warning='自动快照空间不足，请导出 JSON。';}}localStorage.setItem(this.key,JSON.stringify(value));}return value;};next=globalThis.navigator?.locks?await navigator.locks.request(this.name,change):change();
   }
   this.state=next;if(this.db){try{localStorage.setItem(this.key,JSON.stringify(next));}catch{this.warning='主数据库已保存，但镜像空间不足；请导出 JSON 备份。';}}
   this.channel?.postMessage({source:this.source,revision:next.revision});this.onChange({external:false});return next;
  };this.queue=this.queue.catch(()=>{}).then(op);return this.queue;
 }
 async snapshotList(){if(!this.db){try{return JSON.parse(localStorage.getItem(this.name+':snapshots')||'[]').reverse();}catch{return [];}}return new Promise((resolve,reject)=>{const tx=this.db.transaction('snapshots','readonly'),store=tx.objectStore('snapshots'),items=store.getAll(),keys=store.getAllKeys();tx.oncomplete=()=>resolve(items.result.map((x,i)=>({...x,key:keys.result[i]})).reverse());tx.onerror=()=>reject(tx.error);});}
 async replace(data){validateState(data);const replacement=clone(data);replacement.timer=null;return this.mutate(()=>{},{snapshot:true,replacement});}
 async rawRecovery(){let database=null;try{database=this.db?await this.readDB():null;}catch{}let mirror=null;try{mirror=localStorage.getItem(this.key);}catch{}return {database,mirror};}
}
